// <auto-generated />
using System;
using FirstWebApi.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVLookup_WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231009110659_InitDB_and_SeedData")]
    partial class InitDB_and_SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Actived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "33ba4ec9-fbbf-4d3c-a806-45c816a6fa40",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 9, 18, 6, 59, 403, DateTimeKind.Local).AddTicks(1250),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "0f5a098a-5c7a-4b0b-95af-dc8a6bdba1b0",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 9, 18, 6, 59, 403, DateTimeKind.Local).AddTicks(1270),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "280e5e72-a62c-49c9-8e7e-b44842ab2acf",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 9, 18, 6, 59, 403, DateTimeKind.Local).AddTicks(1275),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUser");

                    b.HasData(
                        new
                        {
                            AccountId = "33ba4ec9-fbbf-4d3c-a806-45c816a6fa40",
                            UserId = "d39bc247-3ef6-469f-849b-56646327c29c"
                        },
                        new
                        {
                            AccountId = "0f5a098a-5c7a-4b0b-95af-dc8a6bdba1b0",
                            UserId = "366012b5-fe92-420e-b569-fe77e6b9248e"
                        },
                        new
                        {
                            AccountId = "280e5e72-a62c-49c9-8e7e-b44842ab2acf",
                            UserId = "0d580df3-6df2-4b5e-bb48-64cebbaab088"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introdution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CurriculumVitae");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = "92927f1a-ae2d-4734-a106-54b27a21811c",
                            Name = "Quận Ninh Kiều",
                            ProvinceId = "8ddf76ac-ab34-443d-9241-9c9276112078"
                        },
                        new
                        {
                            Id = "04e88202-9bfa-46fd-8f3d-0eba266234da",
                            Name = "Quận Bình Thuỷ",
                            ProvinceId = "8ddf76ac-ab34-443d-9241-9c9276112078"
                        },
                        new
                        {
                            Id = "d2996998-a3ec-4ee6-99c9-a7ca92a08f77",
                            Name = "Quận Cái Răng",
                            ProvinceId = "8ddf76ac-ab34-443d-9241-9c9276112078"
                        },
                        new
                        {
                            Id = "de7e40b5-d7cf-4289-8884-3317971d1c7b",
                            Name = "Quận Thốt Nốt",
                            ProvinceId = "8ddf76ac-ab34-443d-9241-9c9276112078"
                        },
                        new
                        {
                            Id = "ade91fdc-b619-44bb-9cc6-83875b78038b",
                            Name = "Quận Ô Môn",
                            ProvinceId = "8ddf76ac-ab34-443d-9241-9c9276112078"
                        },
                        new
                        {
                            Id = "68fcd86b-66d8-4d31-bab2-f030e9eeca89",
                            Name = "Quận Liên Chiểu",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "d8a243df-9f32-420d-ba3a-f2ad9483de9a",
                            Name = "Quận Thanh Khê",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "67eb1b5b-29ce-4977-83e3-addf7e9b96f3",
                            Name = "Quận Hải Châu",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "0d4d37a8-82ab-4d11-9ada-ad55db806faa",
                            Name = "Quận Sơn Trà",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "1b2be630-6a58-43d7-9ebd-f0b7fd816c69",
                            Name = "Quận Ngũ Hành Sơn",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "401f0480-b224-4531-b002-59aa6d5f018e",
                            Name = "Quận Cẩm Lệ",
                            ProvinceId = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd"
                        },
                        new
                        {
                            Id = "3d8d0ae2-52f8-4465-b65a-422576a242e6",
                            Name = "Quận Ba Đình",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "03dda874-3d68-4a1d-800f-97436f833d21",
                            Name = "Quận Hoàn Kiếm",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "d48b1533-0067-4aba-9d23-f49d06293df6",
                            Name = "Quận Tây Hồ",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "061a88dd-1b0b-4c36-b372-6073f223877a",
                            Name = "Quận Long Biên",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "b03a1406-2cfb-47a1-86a8-42f781bb6b13",
                            Name = "Quận Cầu Giấy",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "0dea90c5-a34f-42a4-bf6b-733038b11865",
                            Name = "Quận Đống Đa",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "5ad2ce86-3331-4a2f-a265-bacdcb86198a",
                            Name = "Quận Hai Bà Trưng",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "5f6bf0f4-c350-4330-9983-8ad0db03f66d",
                            Name = "Quận Hoàng Mai",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "d8f38a50-7e91-455f-b3bb-0aaa6be092b4",
                            Name = "Quận Thanh Xuân",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "c1907af1-00a6-4624-8102-c3390a393745",
                            Name = "Quận Nam Từ Liêm",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "f87d8618-f14d-40db-89be-ab5db52bdab3",
                            Name = "Quận Bắc Từ Liêm",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "994666da-2a22-42bd-8414-32abbafde8b7",
                            Name = "Quận Hà Đông",
                            ProvinceId = "3afe198a-d1ce-498f-ad37-b6704c68ed6f"
                        },
                        new
                        {
                            Id = "8c7b72c3-564d-4417-903a-cd2e4cb43982",
                            Name = "Quận Hồng Bàng",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "30838ca4-4651-4224-b9a5-e68a5c956c7d",
                            Name = "Quận Ngô Quyền",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "b72d7e07-3c37-4ef2-a0df-f35702023e1a",
                            Name = "Quận Lê Chân",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "3a0847d3-f598-45ae-b020-da265b9d9ba5",
                            Name = "Quận Hải An",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "8bbe91f6-469e-412a-8845-aac8edc8d09b",
                            Name = "Quận Kiến An",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "a2d35d7f-7ccd-41cd-a887-ae937cca4844",
                            Name = "Quận Đồ Sơn",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "1cbe7ac2-4953-4929-ba9e-4a1fbcf9cbb6",
                            Name = "Quận Dương Kinh",
                            ProvinceId = "0d239684-dc20-41ea-acc3-4f8a7f68ead6"
                        },
                        new
                        {
                            Id = "db1a62e1-ced1-4670-b52e-d0357b1c7de0",
                            Name = "Quận 1",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "c014c7f9-b61d-46ca-90fe-726b0f54789d",
                            Name = "Quận 2",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "f16d55e5-1cce-4035-8179-fcc57f0726c8",
                            Name = "Quận 3",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "e91a1a4c-0b82-4d70-b093-72a1220e874b",
                            Name = "Quận 4",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "80e4e198-8ff6-4c24-868e-f9ba8e492157",
                            Name = "Quận 5",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "c2f8ee2d-c239-49e7-a133-9f04998a6bea",
                            Name = "Quận 6",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "98327593-6f37-46b3-b2d1-9dc7c26bb615",
                            Name = "Quận 7",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "1d78ee62-6967-43f7-a697-8f1b2a540d04",
                            Name = "Quận 8",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "9bd813dc-7ebb-479f-ae7b-91a185c2336f",
                            Name = "Quận 9",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "ea4184a5-d2bd-48d2-83b3-d01ffd3cb963",
                            Name = "Quận 10",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "88bba154-f30c-47f5-94b5-0175a8ad8b63",
                            Name = "Quận 11",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "cc26792e-0e33-4965-a574-2d0c1decd71b",
                            Name = "Quận 12",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "8609ef08-a5b2-44a5-874b-4b06593f684e",
                            Name = "Quận Gò Vấp",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "4fc60447-24f3-49d9-8e2b-457f8130e04f",
                            Name = "Quận Bình Thạnh",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "87c12b14-e52d-40db-89ad-d14c8c1c3fba",
                            Name = "Quận Tân Bình",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "4d6154b1-f8e6-4051-93d2-c36d5e9bc627",
                            Name = "Quận Tân Phú",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "d93f6d52-4f42-43f2-961d-b70c2ad69833",
                            Name = "Quận Phú Nhuận",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "1b424a4e-2a04-409a-b278-810e52f82937",
                            Name = "Quận Thủ Đức",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        },
                        new
                        {
                            Id = "4d2b068e-1bbb-41d8-aade-6fc1a2b61ee7",
                            Name = "Quận Bình Tân",
                            ProvinceId = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = "36776cf7-935e-4c3d-96e9-d76208875e15",
                            Exp = "Tất cả kinh nghiệm"
                        },
                        new
                        {
                            Id = "7a869599-f2dc-48b6-83ed-3cfde18b2603",
                            Exp = "Chưa có kinh nghiệm"
                        },
                        new
                        {
                            Id = "16f95d27-e5b9-4f7c-b79a-d1f3bc208d22",
                            Exp = "Dưới 1 năm"
                        },
                        new
                        {
                            Id = "c88a8c53-3a08-4ca9-a755-68a4e62ab221",
                            Exp = "Từ 1-2 năm"
                        },
                        new
                        {
                            Id = "b8b2fa0a-271b-4030-8583-6919fa247662",
                            Exp = "Từ 2-3 năm"
                        },
                        new
                        {
                            Id = "f98830a1-bac9-483a-a2d8-0f097cc395c6",
                            Exp = "Từ 3-5 năm"
                        },
                        new
                        {
                            Id = "a0a2acf9-fbe8-45a5-a499-8ee19eb414f0",
                            Exp = "Từ 5-10 năm"
                        },
                        new
                        {
                            Id = "6e7abc90-fd1a-4bf7-b3ec-a8a95a50bad4",
                            Exp = "Trên 10 năm"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("JobAddress");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobCareer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCareer");

                    b.HasData(
                        new
                        {
                            Id = "ba264947-c504-4937-bee7-f7bb68b997bf",
                            Career = "Tất cả ngành nghề"
                        },
                        new
                        {
                            Id = "a6b90420-cba7-45d4-bb48-e9c40f94aaea",
                            Career = "An toàn lao động"
                        },
                        new
                        {
                            Id = "55a17258-1ae2-4e1c-ac9a-70a6c020a632",
                            Career = "Bán hàng kỹ thuật"
                        },
                        new
                        {
                            Id = "8d802f05-b88d-491d-a313-4fbd43c7351d",
                            Career = "Bán lẻ / bán sỉ"
                        },
                        new
                        {
                            Id = "f92a41db-d020-49d9-8d64-2b453dd6d1d1",
                            Career = "Báo chí / Truyền hình"
                        },
                        new
                        {
                            Id = "93281555-5c78-4897-8f50-87697e8bd6dc",
                            Career = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "275e979f-2df0-49ad-89a0-34da9e2d66a0",
                            Career = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "8b112e3f-3cfc-4acf-84c0-0c4e583f498a",
                            Career = "Bất động sản"
                        },
                        new
                        {
                            Id = "ce7ce54f-917a-41ab-a5ec-b5f4c630257c",
                            Career = "Biên / Phiên dịch"
                        },
                        new
                        {
                            Id = "d3364abd-f53e-421e-b432-9c10a432a4f1",
                            Career = "Bưu chính - Viễn thông"
                        },
                        new
                        {
                            Id = "66a7e467-2858-4419-8afe-9857a083d995",
                            Career = "Chứng khoán / Vàng / Ngoại tệ"
                        },
                        new
                        {
                            Id = "0e2b135a-b963-4615-9f46-228a857d5801",
                            Career = "Cơ khí / Chế tạo / Tự động hóa"
                        },
                        new
                        {
                            Id = "581b0306-e58a-4abc-97bb-f43a4c7a5636",
                            Career = "Công nghệ cao"
                        },
                        new
                        {
                            Id = "79622f86-923a-4025-85d7-d2effe331311",
                            Career = "Công nghệ Ô tô"
                        },
                        new
                        {
                            Id = "e8808e0b-7bd7-4f4d-b88f-a5780b9f5b30",
                            Career = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = "7b0391ba-3d06-4a1f-9142-5ac9005bdd86",
                            Career = "Dầu khí/Hóa chất"
                        },
                        new
                        {
                            Id = "f5146228-507a-4e8b-8935-f807f78494b9",
                            Career = "Dệt may / Da giày"
                        },
                        new
                        {
                            Id = "6f661fb2-1e0d-4961-96eb-540d95ac139b",
                            Career = "Địa chất / Khoáng sản"
                        },
                        new
                        {
                            Id = "63ab4646-f29a-4312-98f0-41e1afb0dcc9",
                            Career = "Dịch vụ khách hàng"
                        },
                        new
                        {
                            Id = "5f7557f9-cc10-4d4c-ab53-158aad162a0a",
                            Career = "Điện / Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "0176c9be-06df-410d-a7ce-ff9d7ea8f6d3",
                            Career = "Điện tử viễn thông"
                        },
                        new
                        {
                            Id = "6db37876-3cbd-405b-ac50-5e6a9daf3cd2",
                            Career = "Du lịch"
                        },
                        new
                        {
                            Id = "62abbd5d-450c-4fb0-8f7c-814cb934a88d",
                            Career = "Dược phẩm / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "2a02a5a9-0b6a-4a88-92dd-952afe3fb2cf",
                            Career = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "0831dca0-ca55-4c24-9ac3-ed773b8394a5",
                            Career = "Hàng cao cấp"
                        },
                        new
                        {
                            Id = "982bc6fd-b987-4c24-a94e-9100df11b737",
                            Career = "Hàng gia dụng"
                        },
                        new
                        {
                            Id = "e8806ebc-e6d6-4f17-88c0-1b277eac4031",
                            Career = "Hàng hải"
                        },
                        new
                        {
                            Id = "d9132219-a4e8-433a-8af2-62eca627d605",
                            Career = "Hàng không"
                        },
                        new
                        {
                            Id = "13b0fd37-8048-4a17-8c39-f5085139364a",
                            Career = "Hàng tiêu dùng"
                        },
                        new
                        {
                            Id = "1f511407-d491-4539-905b-dcb8e449ed00",
                            Career = "Hành chính / Văn phòng"
                        },
                        new
                        {
                            Id = "5f76347c-d027-4f25-8b63-e3897e69f8e4",
                            Career = "Hoá học / Sinh học"
                        },
                        new
                        {
                            Id = "bad756e7-a5f3-41a8-aa01-4791ab6244ba",
                            Career = "Hoạch định / Dự án"
                        },
                        new
                        {
                            Id = "d827e261-2891-474b-84f6-9c4fa0e8d3af",
                            Career = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "ec486182-affe-41d4-a01b-b810b4a49d9c",
                            Career = "IT Phần cứng / Mạng"
                        },
                        new
                        {
                            Id = "94b671d4-0be6-409a-9481-bb4c4bfa9630",
                            Career = "IT phần mềm"
                        },
                        new
                        {
                            Id = "d06f4cf2-3f76-486a-a80a-099ca34c179c",
                            Career = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "7cdd803d-98fa-4f4c-aa0b-7fcd1659d20d",
                            Career = "Khách sạn / Nhà hàng"
                        },
                        new
                        {
                            Id = "289870ea-2021-4f6b-9740-e6b6f19f4bd2",
                            Career = "Kiến trúc"
                        },
                        new
                        {
                            Id = "f1b7e519-24e7-4b26-bdc2-c7d3f24dcc53",
                            Career = "Kinh doanh / Bán hàng"
                        },
                        new
                        {
                            Id = "3e61bc18-dfac-4381-be0a-8f8c581c1dca",
                            Career = "Logistics"
                        },
                        new
                        {
                            Id = "5896b9c4-88a9-42a2-885f-7426597447e6",
                            Career = "Luật / Pháp lý"
                        },
                        new
                        {
                            Id = "b1e13567-5bd6-427a-b951-4de88915c688",
                            Career = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "2a21c955-ce63-45e4-bd54-890c8ebbd7ab",
                            Career = "Môi trường / Xử lý chất thải"
                        },
                        new
                        {
                            Id = "aaf1ed97-167c-46bc-b662-d220be12a60c",
                            Career = "Mỹ phẩm / Trang sức"
                        },
                        new
                        {
                            Id = "b401f385-88e6-4156-b15b-4525bcca7dcd",
                            Career = "Mỹ thuật / Nghệ thuật / Điện ảnh"
                        },
                        new
                        {
                            Id = "c430f00a-0cab-468c-a3cc-035ccbed6852",
                            Career = "Ngân hàng / Tài chính"
                        },
                        new
                        {
                            Id = "cbbb8b5b-41a7-4e70-aadd-5615aa7c4f52",
                            Career = "Ngành nghề khác"
                        },
                        new
                        {
                            Id = "bfe3b6f8-c66f-4290-8a3d-90d72a955d9a",
                            Career = "NGO / Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "04e88e82-8ad5-4d1e-9a35-a06d802a94d0",
                            Career = "Nhân sự"
                        },
                        new
                        {
                            Id = "5f7079e4-56bd-4817-a687-9e11353fd895",
                            Career = "Nông / Lâm / Ngư nghiệp"
                        },
                        new
                        {
                            Id = "52b420b7-2c6c-425b-b494-e168d7c78df6",
                            Career = "Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "18a66050-e797-45d9-9673-478be96367e3",
                            Career = "Quản lý chất lượng (QA/QC)"
                        },
                        new
                        {
                            Id = "21a25a3f-07ba-4305-9cff-52d5d4e3947f",
                            Career = "Quản lý điều hành"
                        },
                        new
                        {
                            Id = "1d9ea4e8-31f0-4dc7-b56d-56a85c98966a",
                            Career = "Sản phẩm công nghiệp"
                        },
                        new
                        {
                            Id = "eef5210b-7fd6-43ec-867e-ff207d2804fa",
                            Career = "Sản xuất"
                        },
                        new
                        {
                            Id = "ea2aeffb-9a99-4bca-9353-6902195240e2",
                            Career = "Spa / Làm đẹp"
                        },
                        new
                        {
                            Id = "9e2cd06a-fff4-440a-84bb-734828a26143",
                            Career = "Tài chính / Đầu tư"
                        },
                        new
                        {
                            Id = "833a5064-3817-44ff-9ba8-d9d02fe684b9",
                            Career = "Thiết kế đồ họa"
                        },
                        new
                        {
                            Id = "0808697e-dae7-4eba-9794-178ad3e01856",
                            Career = "Thiết kế nội thất"
                        },
                        new
                        {
                            Id = "4c575d7a-a1c8-48ef-945b-5b298dbc9065",
                            Career = "Thời trang"
                        },
                        new
                        {
                            Id = "cbee0006-eb94-46ca-8a80-90c150543107",
                            Career = "Thư ký / Trợ lý"
                        },
                        new
                        {
                            Id = "558abb40-4b8f-4e73-a70c-9edb615bdbaf",
                            Career = "Thực phẩm / Đồ uống"
                        },
                        new
                        {
                            Id = "940cf5c8-3e4d-4bce-8892-4e387917827f",
                            Career = "Tổ chức sự kiện / Quà tặng"
                        },
                        new
                        {
                            Id = "23f50555-84b6-4319-821e-ebecc48a2b33",
                            Career = "Tư vấn"
                        },
                        new
                        {
                            Id = "f8f1d3db-2d59-41ea-ab2e-ec99d0cee089",
                            Career = "Vận tải / Kho vận"
                        },
                        new
                        {
                            Id = "0dc765e1-4a05-4ce4-9918-61ca15d4af75",
                            Career = "Xây dựng"
                        },
                        new
                        {
                            Id = "e5e3cb14-d4b3-4f66-8c15-e881f6895430",
                            Career = "Xuất nhập khẩu"
                        },
                        new
                        {
                            Id = "ce7fd462-68c9-45eb-9261-c07946691dab",
                            Career = "Y tế / Dược"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobField");

                    b.HasData(
                        new
                        {
                            Id = "8ca3c201-ed61-4f72-8bc4-a47f242d8b83",
                            Field = "Tất cả lĩnh vực"
                        },
                        new
                        {
                            Id = "da06b13c-b950-4cae-97fc-416d645074df",
                            Field = "Agency (Design/Development)"
                        },
                        new
                        {
                            Id = "c5fb1aa2-f040-429d-9939-b22cc49509a5",
                            Field = "Agency (Marketing/Advertising)"
                        },
                        new
                        {
                            Id = "4ff641c7-1792-4fda-9670-bb58f9fc62ae",
                            Field = "Bán lẻ - Hàng tiêu dùng - FMCG"
                        },
                        new
                        {
                            Id = "71ff2896-8da6-47cb-ad5f-a83f7e647032",
                            Field = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "39b5acb7-455f-46a9-b640-b87f59a1d6ea",
                            Field = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "d5843946-32d1-4f1f-afc6-cb32e050ff98",
                            Field = "Bất động sản"
                        },
                        new
                        {
                            Id = "766f1e1e-5a42-47a7-abbf-7df1ad309965",
                            Field = "Chứng khoán"
                        },
                        new
                        {
                            Id = "23641674-3f54-485a-8015-4408c8c9f234",
                            Field = "Cơ khí"
                        },
                        new
                        {
                            Id = "504a9700-0877-4278-8bf1-6ce557c9a1ba",
                            Field = "Cơ quan nhà nước"
                        },
                        new
                        {
                            Id = "00561e36-0ab4-4d51-a02e-6f6c7d4df039",
                            Field = "Du lịch"
                        },
                        new
                        {
                            Id = "f20bc70d-2dd5-49cb-a4a4-825d7bac75de",
                            Field = "Dược phẩm / Y tế / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "cf9390c1-5e33-42f0-ba70-5cfd510bf1a0",
                            Field = "Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "ed2b1728-fab1-4f8b-a13b-8c5701e5f7cf",
                            Field = "Giải trí"
                        },
                        new
                        {
                            Id = "5b05f04e-fe17-4fe0-86d5-af4b7022f592",
                            Field = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "5fe0ceae-1e96-4b37-a730-e2deb04ac57e",
                            Field = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "887b25fb-0012-4113-863d-8f57e225798a",
                            Field = "Internet / Online"
                        },
                        new
                        {
                            Id = "3625aef5-b62c-4f4f-b356-78b38aa46218",
                            Field = "IT - Phần cứng"
                        },
                        new
                        {
                            Id = "991513af-0bc0-439e-8af6-8eb2b8011ad1",
                            Field = "IT - Phần mềm"
                        },
                        new
                        {
                            Id = "218078f2-3667-4ab7-b446-851de11bdb88",
                            Field = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "18061e67-d1a6-4bd8-bf0d-3f87d638e8df",
                            Field = "Khác"
                        },
                        new
                        {
                            Id = "af06ef24-ca2d-4ee9-bb04-26030d1bc04e",
                            Field = "Logistics - Vận tải"
                        },
                        new
                        {
                            Id = "30bba1f1-a7a0-4f5d-adef-02c66fcb63d7",
                            Field = "Luật"
                        },
                        new
                        {
                            Id = "36e5638f-89db-4fc5-802d-fd621a363ca0",
                            Field = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "7b56c84d-f468-4ac4-9442-47b4e0890cd6",
                            Field = "Môi trường"
                        },
                        new
                        {
                            Id = "ef25cad1-3762-4a81-acc2-b2e545204023",
                            Field = "Năng lượng"
                        },
                        new
                        {
                            Id = "f9c507b7-78bb-4f0b-9dc9-75314359e52f",
                            Field = "Ngân hàng"
                        },
                        new
                        {
                            Id = "e53e0ef6-0876-4f46-85c3-70a77ee34654",
                            Field = "Nhà hàng / Khách sạn"
                        },
                        new
                        {
                            Id = "fd0bceac-b8f5-4f36-84ec-08a80cd2f870",
                            Field = "Nhân sự"
                        },
                        new
                        {
                            Id = "ecd658f5-bda1-415d-bc45-c54c2e10bcaf",
                            Field = "Nông Lâm Ngư nghiệp"
                        },
                        new
                        {
                            Id = "7dd5f3c3-c788-4bab-9325-99ad14aad5a8",
                            Field = "Sản xuất"
                        },
                        new
                        {
                            Id = "38e29d25-11f2-4d16-ace1-40e0cb3163af",
                            Field = "Tài chính"
                        },
                        new
                        {
                            Id = "e99f2cc2-df48-46b0-a25f-20c94aff5233",
                            Field = "Thiết kế / kiến trúc"
                        },
                        new
                        {
                            Id = "fbe83070-c09a-4938-8e68-995b43c762a9",
                            Field = "Thời trang"
                        },
                        new
                        {
                            Id = "4e2d10ce-95cd-40f9-9c56-fb2e2242a7a5",
                            Field = "Thương mại điện tử"
                        },
                        new
                        {
                            Id = "8049a3c8-159e-4f0b-b1c3-18bf10396dcd",
                            Field = "Tổ chức phi lợi nhuận"
                        },
                        new
                        {
                            Id = "93a2196d-c17e-4919-90af-2bc8200e2a9c",
                            Field = "Tự động hóa"
                        },
                        new
                        {
                            Id = "59a4a776-bc0a-4309-ba01-72f917b11222",
                            Field = "Tư vấn"
                        },
                        new
                        {
                            Id = "1ddbaf9c-9cd2-4505-994b-b89683313d2b",
                            Field = "Viễn thông"
                        },
                        new
                        {
                            Id = "9963c8e7-f960-4856-9991-a4a213c3cb8f",
                            Field = "Xây dựng"
                        },
                        new
                        {
                            Id = "ddeb0dc5-124e-44f3-ab00-1794fb39eb56",
                            Field = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobForm");

                    b.HasData(
                        new
                        {
                            Id = "281912d9-adff-4871-b64a-17bc6b2768e7",
                            Form = "Tất cả hình thức"
                        },
                        new
                        {
                            Id = "0b897c49-6b51-4a94-8372-b3251ed14034",
                            Form = "Toàn thời gian"
                        },
                        new
                        {
                            Id = "06bf76e3-f80e-44df-9e91-c661ec0707ce",
                            Form = "Bán thời gian"
                        },
                        new
                        {
                            Id = "d21317e2-e1f4-489c-b9da-b25a5cc1549f",
                            Form = "Thực tập"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosition");

                    b.HasData(
                        new
                        {
                            Id = "becd4e2b-ed75-48bd-b213-44e54b1fae61",
                            Position = "Tất cả vị trí"
                        },
                        new
                        {
                            Id = "a4e10d23-95d8-48e6-bdad-b7bad392f69f",
                            Position = "Nhân viên"
                        },
                        new
                        {
                            Id = "9652fe6a-d6aa-4810-a6d9-0cf3a745724f",
                            Position = "Trưởng nhóm"
                        },
                        new
                        {
                            Id = "cd57484a-d201-4712-93a5-b5ccdcc01390",
                            Position = "Trưởng / Phó phòng"
                        },
                        new
                        {
                            Id = "d5b614e3-ffa5-41e8-bf3b-83a78f20ee7c",
                            Position = "Quản lí / Giám sát"
                        },
                        new
                        {
                            Id = "95c0b1d6-d535-4172-b822-64ed6838b0fb",
                            Position = "Trưởng chi nhánh"
                        },
                        new
                        {
                            Id = "fc354f31-97fc-4fce-a530-2a44f7b00783",
                            Position = "Phó giám đốc"
                        },
                        new
                        {
                            Id = "13798407-04d4-4f25-ad79-6254044f9bda",
                            Position = "Giám đốc"
                        },
                        new
                        {
                            Id = "7c5b0f9f-a4a5-4562-bcd8-c1e434b96e50",
                            Position = "Thực tập sinh"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = "d0b466ed-ff73-4f78-9c8b-412228ba7efb",
                            Name = "Tất cả tỉnh thành"
                        },
                        new
                        {
                            Id = "35f0e62a-1c78-41e7-89aa-bd5b3b80f08d",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = "42361adb-d19e-4ed5-8255-706331162e74",
                            Name = "Bà Rịa-Vũng Tàu"
                        },
                        new
                        {
                            Id = "c2899e3d-4fa0-49e8-ad5c-0b0dc33fbe07",
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = "16e240b8-aa51-40d7-bf17-2253a33d8df3",
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = "4c17a715-7b0d-45a0-a140-271f83c1edbd",
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = "89f4f74b-66fb-4d56-9edd-3bb25cd67fda",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = "a385b3d1-a3d9-487d-8dda-0931c3ed77a0",
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = "cd898b19-d120-4cb9-9f57-508cc876b333",
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = "7c437a52-172e-4780-9606-c44e802960f2",
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = "e06b6f23-8ad1-4ef4-b0d3-8dddedd2f47a",
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = "916f4248-36c0-43d0-b07c-357f58de2ac9",
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = "0e8e9967-8cab-4f3f-9fba-f753e4c8c958",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = "8ddf76ac-ab34-443d-9241-9c9276112078",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = "cd5a411e-d1e1-457c-9c9a-6cbe048f771f",
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = "cd90b2d4-e87b-4f75-bdcc-d7ed8793eebd",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = "b9f084d9-3154-4bdb-8fc4-b826a47984ea",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = "db1566ca-010c-4a21-a56b-039812d35a21",
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = "5cbb4477-d369-4afc-9af8-ead5fe4a6104",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = "fec1c769-878b-4013-b1f0-8aa913599ad7",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = "97885809-ca5f-4946-97f6-05f85a95549f",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = "e3513de1-5e0c-4db0-9923-c8be8b556720",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = "059c9af0-2cd1-4b3a-bcdb-c75edef5fad9",
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = "d297e516-cb35-480b-bf22-774a0c78ee25",
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = "3afe198a-d1ce-498f-ad37-b6704c68ed6f",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = "b7806adc-522f-4086-9f5c-2f401bd1c90f",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = "82505675-1bda-471d-aef4-ccf80d0c8a66",
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = "0d239684-dc20-41ea-acc3-4f8a7f68ead6",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = "9cd166d1-1169-4839-bd98-7d4cd1e4d745",
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = "efe98dbf-7318-409f-b72e-2e56e4f1378f",
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = "3bb8c0a0-b82e-4a71-a47f-a945e029442b",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = "2b5f295e-b576-46d5-af70-6b926175bc53",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = "30a9912c-5c36-4c23-8145-9dfbb9ba307d",
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = "9e39e4c8-43c2-4396-ba89-993e402c534e",
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = "6b14ec54-14b1-4865-ad18-2a0af7837ea3",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = "b8bf4a27-7f6a-40e7-ab4b-095da9d9b170",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = "bfeb546e-77be-458f-a3a2-5c62edda231c",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = "bb430296-b41f-4e75-9086-e3bc6999addd",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = "7de1a111-7c7e-4379-974c-199d94fbe5d2",
                            Name = "Long An"
                        },
                        new
                        {
                            Id = "6c230a0d-5b3f-4a24-8d87-e6e2356cf3ae",
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = "4f4c6b8a-3577-4d2e-8349-9748f0dcd07a",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = "f4f58cff-9859-4b91-98eb-34a14e9dfaa0",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = "04172533-2166-4a7e-8287-b9c89a2d81c1",
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = "0937eebe-f67b-43af-9f9f-77c5cdd014b0",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = "732049db-e4f4-49f8-927b-804fc4a16a1b",
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = "a5b0e62a-42f3-4845-89c1-b294ce3b0ea5",
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = "16dc3a6d-902d-4b4d-a449-0199b08d2782",
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = "f90b1642-f8b3-4996-82d9-59a9bf461702",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = "6cdf7c53-42b1-47f3-9ad9-3c61ee47fb3e",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = "692cc64d-b902-42e9-afed-dbfa2cd1d28f",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = "0d7ff715-8e06-45e9-8424-bdccdcfc266f",
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = "2adab348-36d2-4b29-a157-ee493b4c6127",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = "2f3f2353-13f6-48ef-96f8-96fb9c9939be",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = "5d30d59d-f492-4ea4-9b37-85f43d7f73a8",
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = "6223ca1b-b550-4db2-bcf8-a100f3c49be1",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = "ee0d56d3-b315-48e4-9f4c-e009069634e9",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = "977a33ef-a1a4-481a-8a75-32d51206177e",
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = "251d7a46-c39d-4489-9341-250bf72a6f4d",
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = "d30ca515-a7f3-4ef6-ba36-fb55b62db0bc",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = "2e8feaee-6f76-4af3-816d-0ba60ab7bcfb",
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = "07bc25b1-c179-45a4-b728-cc6c2d8a9df2",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = "3b6a128f-156d-4bc6-b2f2-0cba45905b78",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = "5e6ead12-869b-48d5-864d-a13d4c96a588",
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = "76f5ce8a-ea54-431c-b442-0e29f22d7180",
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("JobAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobCareerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobFieldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobPositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("JobCareerId");

                    b.HasIndex("JobFieldId");

                    b.HasIndex("JobFormId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.Property<string>("RecruitmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurriculumVitaeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecruitmentId", "CurriculumVitaeId");

                    b.HasIndex("CurriculumVitaeId");

                    b.ToTable("RecruitmentCV");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "16618d2a-15fc-4908-a250-9574b22a3897",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "1919974e-0d95-480f-926a-10399c222d22",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            Id = "2f90ac56-1794-4c62-b0be-a025e7e61291",
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "d39bc247-3ef6-469f-849b-56646327c29c",
                            Email = "cvlookup.sgu.2023@gmail.com"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = "16618d2a-15fc-4908-a250-9574b22a3897",
                            UserId = "d39bc247-3ef6-469f-849b-56646327c29c"
                        },
                        new
                        {
                            RoleId = "2f90ac56-1794-4c62-b0be-a025e7e61291",
                            UserId = "366012b5-fe92-420e-b569-fe77e6b9248e"
                        },
                        new
                        {
                            RoleId = "1919974e-0d95-480f-926a-10399c222d22",
                            UserId = "0d580df3-6df2-4b5e-bb48-64cebbaab088"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Candidate", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Candidate");

                    b.HasData(
                        new
                        {
                            Id = "0d580df3-6df2-4b5e-bb48-64cebbaab088",
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            LastName = "CVLookup"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Employer", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employer");

                    b.HasData(
                        new
                        {
                            Id = "366012b5-fe92-420e-b569-fe77e6b9248e",
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            Address = "Admin",
                            Description = "Admin",
                            EmployerName = "Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobAddress", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobCareer", "JobCareer")
                        .WithMany()
                        .HasForeignKey("JobCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobField", "JobField")
                        .WithMany()
                        .HasForeignKey("JobFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobForm", "JobForm")
                        .WithMany()
                        .HasForeignKey("JobFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Experience");

                    b.Navigation("JobAddress");

                    b.Navigation("JobCareer");

                    b.Navigation("JobField");

                    b.Navigation("JobForm");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.CurriculumVitae", "CurriculumVitae")
                        .WithMany()
                        .HasForeignKey("CurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVitae");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
