// <auto-generated />
using System;
using FirstWebApi.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVLookup_WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231112180402_InitDb_and_SeedData")]
    partial class InitDb_and_SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Actived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "89329e50-d4f7-4213-9fd7-ab003b0eb205",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 13, 1, 4, 1, 594, DateTimeKind.Local).AddTicks(2189),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "efbe352e-358a-4086-bc17-3bbf6c7573f1",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 13, 1, 4, 1, 594, DateTimeKind.Local).AddTicks(2215),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "e37b0e74-590b-490e-9cca-f3b5165f80bc",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 13, 1, 4, 1, 594, DateTimeKind.Local).AddTicks(2226),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUser");

                    b.HasData(
                        new
                        {
                            AccountId = "89329e50-d4f7-4213-9fd7-ab003b0eb205",
                            UserId = "2f5ef746-7f88-47d8-8534-35fe1b30ecba"
                        },
                        new
                        {
                            AccountId = "efbe352e-358a-4086-bc17-3bbf6c7573f1",
                            UserId = "8b5e30c2-1c4e-40f5-b468-738c8a7cc4e1"
                        },
                        new
                        {
                            AccountId = "e37b0e74-590b-490e-9cca-f3b5165f80bc",
                            UserId = "ae178b22-9c1a-47b7-818b-db40326c770b"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introdution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CurriculumVitae");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = "256156b9-2c49-4773-8988-077663503a1a",
                            Name = "Quận Ninh Kiều",
                            ProvinceId = "fc28f72f-b153-44c6-8b82-b19ce9a33e27"
                        },
                        new
                        {
                            Id = "5e1c20de-380c-47e1-93df-41e002500674",
                            Name = "Quận Bình Thuỷ",
                            ProvinceId = "fc28f72f-b153-44c6-8b82-b19ce9a33e27"
                        },
                        new
                        {
                            Id = "da0c2617-c02b-446e-96e2-b209f371917e",
                            Name = "Quận Cái Răng",
                            ProvinceId = "fc28f72f-b153-44c6-8b82-b19ce9a33e27"
                        },
                        new
                        {
                            Id = "2a513834-ab4a-4193-9382-1e04ed24c5d4",
                            Name = "Quận Thốt Nốt",
                            ProvinceId = "fc28f72f-b153-44c6-8b82-b19ce9a33e27"
                        },
                        new
                        {
                            Id = "a8762387-ce40-414c-b12c-ac23931751da",
                            Name = "Quận Ô Môn",
                            ProvinceId = "fc28f72f-b153-44c6-8b82-b19ce9a33e27"
                        },
                        new
                        {
                            Id = "c26fded1-a3a2-4e35-826e-84f1e1af4780",
                            Name = "Quận Liên Chiểu",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "cd69284d-c4ba-4c61-b12b-9873f675ce68",
                            Name = "Quận Thanh Khê",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "d9253a19-250d-435f-be06-37926de2fb43",
                            Name = "Quận Hải Châu",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "512e0f37-e6f8-49d8-b05e-c6a58f541af6",
                            Name = "Quận Sơn Trà",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "479992c8-ec10-4d02-9c79-5955ca13cf62",
                            Name = "Quận Ngũ Hành Sơn",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "879693ba-8d46-4780-bbaa-114276d13717",
                            Name = "Quận Cẩm Lệ",
                            ProvinceId = "5370a4af-f42f-4995-8b10-488a9e718932"
                        },
                        new
                        {
                            Id = "4aca9b43-6fcc-40de-a222-9d88ca79f036",
                            Name = "Quận Ba Đình",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "40bce067-2265-4a20-bdff-b3b040c6d9ae",
                            Name = "Quận Hoàn Kiếm",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "a7bd8b5f-cdda-41a8-b429-b0c127ec1032",
                            Name = "Quận Tây Hồ",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "663e9f8f-491c-4b63-b54b-48a17e1e0ab5",
                            Name = "Quận Long Biên",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "2ffafb85-3f31-4c90-9cee-51e3b6176b0d",
                            Name = "Quận Cầu Giấy",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "8da17dcc-4af7-4e3e-9f52-5e28100bf2e3",
                            Name = "Quận Đống Đa",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "1b422bf6-10e0-423e-84cc-c879b0853b78",
                            Name = "Quận Hai Bà Trưng",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "29dc0db0-67eb-404f-b20f-fd1daf33a0a5",
                            Name = "Quận Hoàng Mai",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "0267b039-11da-4397-9e9c-7a22249830a3",
                            Name = "Quận Thanh Xuân",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "019bd758-889e-41e7-b11c-9fff8fd8ffc3",
                            Name = "Quận Nam Từ Liêm",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "46f486b8-a40a-44af-823d-2f5859766d13",
                            Name = "Quận Bắc Từ Liêm",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "f7aa60c7-0ec2-4b9a-83e7-da01ac745f54",
                            Name = "Quận Hà Đông",
                            ProvinceId = "f398027c-146d-405d-9897-64ca5a10d6e0"
                        },
                        new
                        {
                            Id = "8543b9d4-449f-4af0-95a4-5c16ef789cdb",
                            Name = "Quận Hồng Bàng",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "dd1d97cc-2dfa-4a2b-ad6a-eaa5fecbea09",
                            Name = "Quận Ngô Quyền",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "73218960-3c74-4b1d-9e04-57d52139ae31",
                            Name = "Quận Lê Chân",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "7fccd9e2-1cb1-4b04-b6d5-8fada81a27a9",
                            Name = "Quận Hải An",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "3b54810b-426a-42e2-aa14-065e10277891",
                            Name = "Quận Kiến An",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "79b78f54-4744-47f4-9f89-2ab077b054d1",
                            Name = "Quận Đồ Sơn",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "b3bc88e3-1c42-4a38-9df1-1911f3edafae",
                            Name = "Quận Dương Kinh",
                            ProvinceId = "0a8f678d-7149-42f6-8e4e-4d03ea01900b"
                        },
                        new
                        {
                            Id = "ba36a2f8-a327-4f8e-a6ff-2fd8a8f8c982",
                            Name = "Quận 1",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "f16fe043-6f6c-4311-8a3e-8b59e94fd931",
                            Name = "Quận 2",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "bae7b491-7020-43bc-b0c7-7d8d9132e812",
                            Name = "Quận 3",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "f76571e6-1a11-41b7-abf4-274b9c78e14f",
                            Name = "Quận 4",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "db356118-53eb-4861-87fa-5a52b76ec422",
                            Name = "Quận 5",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "13b414e6-abdf-4316-8a05-42846846a6f5",
                            Name = "Quận 6",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "102930c3-9235-47c1-8405-ed5a233ceca5",
                            Name = "Quận 7",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "1a7c95d6-9ecc-4273-a573-d44755ede1d8",
                            Name = "Quận 8",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "203f3d13-a2ef-43a1-afd3-8b19f60f677e",
                            Name = "Quận 9",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "dafceccb-7d71-47e7-9094-02006e54ec6d",
                            Name = "Quận 10",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "77a1608b-32a3-4151-9dbf-0ea82d5b0f13",
                            Name = "Quận 11",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "e5df3003-aaf6-487e-8add-f76b7b7a4a66",
                            Name = "Quận 12",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "af887a0e-09d2-45fb-8219-9cf91d584440",
                            Name = "Quận Gò Vấp",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "0297f1d5-53b9-4a3d-9dc0-22609959398d",
                            Name = "Quận Bình Thạnh",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "dc84efcb-67ab-40f2-a36f-546f6b1e717a",
                            Name = "Quận Tân Bình",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "8391ed7a-32c4-404e-8515-503ccd039d19",
                            Name = "Quận Tân Phú",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "ec50872a-009a-44f3-a4b0-247b9d30fae9",
                            Name = "Quận Phú Nhuận",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "c0c61cd5-c4fa-425e-ac91-c2c7af91814a",
                            Name = "Quận Thủ Đức",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        },
                        new
                        {
                            Id = "a79b029f-a363-441b-93ec-c3991622a63e",
                            Name = "Quận Bình Tân",
                            ProvinceId = "9653896f-cc7d-422b-959b-30cda4d02ea0"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = "54e3869e-1c25-41e8-b9e3-66d7f6538a4c",
                            Exp = "Tất cả kinh nghiệm"
                        },
                        new
                        {
                            Id = "d00e4791-3dcf-4b75-8b0d-f1a28d957cad",
                            Exp = "Chưa có kinh nghiệm"
                        },
                        new
                        {
                            Id = "dc102bd2-291c-475a-8387-1252f6818568",
                            Exp = "Dưới 1 năm"
                        },
                        new
                        {
                            Id = "8b71ec80-31cd-43fc-9fba-67bcae6c3ae1",
                            Exp = "Từ 1-2 năm"
                        },
                        new
                        {
                            Id = "b7215014-34a0-44e5-ba81-37ea940f5226",
                            Exp = "Từ 2-3 năm"
                        },
                        new
                        {
                            Id = "ab4192bf-27bf-40e2-b11d-e749f4413121",
                            Exp = "Từ 3-5 năm"
                        },
                        new
                        {
                            Id = "d518a820-d071-4ea7-9b35-d81f8d2228b7",
                            Exp = "Từ 5-10 năm"
                        },
                        new
                        {
                            Id = "f2abc6c4-96a8-47be-b9f6-46ed7a3a31df",
                            Exp = "Trên 10 năm"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.HubConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HubConnection");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("JobAddress");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobCareer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCareer");

                    b.HasData(
                        new
                        {
                            Id = "8408029d-cb7d-4cd7-bad5-09fccb42c0f3",
                            Career = "Tất cả ngành nghề"
                        },
                        new
                        {
                            Id = "88e1a1d5-c90c-4e80-804e-c2167bd2b487",
                            Career = "An toàn lao động"
                        },
                        new
                        {
                            Id = "097f9f0a-3e6d-4444-b3a0-0c3ebee06180",
                            Career = "Bán hàng kỹ thuật"
                        },
                        new
                        {
                            Id = "96354bcc-978f-4f5f-9cc2-043d9d63b6b0",
                            Career = "Bán lẻ / bán sỉ"
                        },
                        new
                        {
                            Id = "56945323-96d9-4868-913f-190ddd432658",
                            Career = "Báo chí / Truyền hình"
                        },
                        new
                        {
                            Id = "b60b445b-a537-4b70-b77f-04359b705ffe",
                            Career = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "8c7e99f1-b8b1-4314-9a35-adcc069850bb",
                            Career = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "7f7ee291-d5a4-45c2-a252-6b5f87f43cd7",
                            Career = "Bất động sản"
                        },
                        new
                        {
                            Id = "ba8e5d25-fc93-4250-980f-5c3ce75c7dfe",
                            Career = "Biên / Phiên dịch"
                        },
                        new
                        {
                            Id = "c1e7fff6-2b4b-4adb-91bd-8c4ba782b386",
                            Career = "Bưu chính - Viễn thông"
                        },
                        new
                        {
                            Id = "66dd6280-c838-4f7d-b606-005e16614d10",
                            Career = "Chứng khoán / Vàng / Ngoại tệ"
                        },
                        new
                        {
                            Id = "332dbeeb-3973-4058-8580-a3c16df8a51d",
                            Career = "Cơ khí / Chế tạo / Tự động hóa"
                        },
                        new
                        {
                            Id = "45420419-8a69-4429-adfc-b1980137a14c",
                            Career = "Công nghệ cao"
                        },
                        new
                        {
                            Id = "20f0f79d-c15b-42fe-be5a-5aa94bc94f36",
                            Career = "Công nghệ Ô tô"
                        },
                        new
                        {
                            Id = "896c5520-8628-424d-9098-68ca6b228449",
                            Career = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = "4304f4a1-8643-442d-b18d-fd8298de540e",
                            Career = "Dầu khí/Hóa chất"
                        },
                        new
                        {
                            Id = "268f562c-1a5f-4108-9817-26bc4ee29e5d",
                            Career = "Dệt may / Da giày"
                        },
                        new
                        {
                            Id = "1659dffb-7325-48f1-b125-6999c0ac13ec",
                            Career = "Địa chất / Khoáng sản"
                        },
                        new
                        {
                            Id = "c44493a5-032c-4bcf-92a0-559115797d6e",
                            Career = "Dịch vụ khách hàng"
                        },
                        new
                        {
                            Id = "a1fa2548-6d49-4195-afd9-9a88a461aae4",
                            Career = "Điện / Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "bf2146a7-3fd0-478a-a9b0-a3027f5f4904",
                            Career = "Điện tử viễn thông"
                        },
                        new
                        {
                            Id = "9f60a834-549d-4ba3-9364-259deb199cc1",
                            Career = "Du lịch"
                        },
                        new
                        {
                            Id = "702d192e-b778-4712-848e-7d5a25b2e3e0",
                            Career = "Dược phẩm / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "2c49eb46-a9d3-4f55-ade1-ef976e0d41f6",
                            Career = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "1a39611e-aa36-43b2-bfc1-8d367acefa1d",
                            Career = "Hàng cao cấp"
                        },
                        new
                        {
                            Id = "b8cb0576-060f-42b0-8768-5cf990968a5e",
                            Career = "Hàng gia dụng"
                        },
                        new
                        {
                            Id = "f19d3fc6-ae1a-4caf-9f65-ab7ca95f5005",
                            Career = "Hàng hải"
                        },
                        new
                        {
                            Id = "9f9e68ea-2727-47fa-b151-b5cd032cb2d3",
                            Career = "Hàng không"
                        },
                        new
                        {
                            Id = "843d43cf-e9dd-4aeb-b3bb-653bbd6f6d8b",
                            Career = "Hàng tiêu dùng"
                        },
                        new
                        {
                            Id = "668e9b53-2685-43c5-97c1-36a059472473",
                            Career = "Hành chính / Văn phòng"
                        },
                        new
                        {
                            Id = "22f297c2-4557-4a3d-bc72-7bcb4c2cbcd5",
                            Career = "Hoá học / Sinh học"
                        },
                        new
                        {
                            Id = "321d9e40-f81f-4ff0-9baa-3434bfc6d421",
                            Career = "Hoạch định / Dự án"
                        },
                        new
                        {
                            Id = "636e7c5f-0ff8-4ff3-99a6-a5df6c1f812b",
                            Career = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "7475a4f3-4e08-480f-8572-0422f54955b5",
                            Career = "IT Phần cứng / Mạng"
                        },
                        new
                        {
                            Id = "ff756adb-6905-45d6-b224-e94fcc9740c7",
                            Career = "IT phần mềm"
                        },
                        new
                        {
                            Id = "6eff5624-9dcb-4c2d-88b7-969036db4ce0",
                            Career = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "71423cb5-b76c-4111-9561-ff4199745796",
                            Career = "Khách sạn / Nhà hàng"
                        },
                        new
                        {
                            Id = "fe2f3fe4-4b07-427f-9f99-5b1d64203021",
                            Career = "Kiến trúc"
                        },
                        new
                        {
                            Id = "c1ff9db0-2754-4387-9350-421563ce4cec",
                            Career = "Kinh doanh / Bán hàng"
                        },
                        new
                        {
                            Id = "1265617a-6b79-4395-8a0f-4623afb89ee8",
                            Career = "Logistics"
                        },
                        new
                        {
                            Id = "8a795da2-6707-46b3-9cbb-eeaff86381df",
                            Career = "Luật / Pháp lý"
                        },
                        new
                        {
                            Id = "71beb573-bfac-48ab-8922-14650282147e",
                            Career = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "61e04550-b81c-4974-9087-72792def1129",
                            Career = "Môi trường / Xử lý chất thải"
                        },
                        new
                        {
                            Id = "fcbe1436-6225-4e10-ad1a-88be8a8709ca",
                            Career = "Mỹ phẩm / Trang sức"
                        },
                        new
                        {
                            Id = "0d78c5dc-c543-468e-afb4-1b3c11935faf",
                            Career = "Mỹ thuật / Nghệ thuật / Điện ảnh"
                        },
                        new
                        {
                            Id = "3eba281d-7a0f-423e-9f9e-a06024937c49",
                            Career = "Ngân hàng / Tài chính"
                        },
                        new
                        {
                            Id = "0b279e16-9680-47bf-a2fe-ea3a905bedd1",
                            Career = "Ngành nghề khác"
                        },
                        new
                        {
                            Id = "3067e8de-ddc0-40f7-a4f2-3ef9b972f1ac",
                            Career = "NGO / Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "bfd62ce0-b1b0-43af-8d48-154191c9e31f",
                            Career = "Nhân sự"
                        },
                        new
                        {
                            Id = "aba754db-f09e-4d62-a1ba-35dc36d9654b",
                            Career = "Nông / Lâm / Ngư nghiệp"
                        },
                        new
                        {
                            Id = "af080787-ff34-4ad5-adb7-b5c29aa5adb7",
                            Career = "Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "c5b7dcc9-3d4e-4a5e-bb1a-5cf6d8312754",
                            Career = "Quản lý chất lượng (QA/QC)"
                        },
                        new
                        {
                            Id = "d6329843-b2f4-4e64-914d-8e095d4f7754",
                            Career = "Quản lý điều hành"
                        },
                        new
                        {
                            Id = "9e3ae632-fbd4-463b-b436-b642f82e6588",
                            Career = "Sản phẩm công nghiệp"
                        },
                        new
                        {
                            Id = "43ec5328-56de-4544-b47d-f5c8336dbec8",
                            Career = "Sản xuất"
                        },
                        new
                        {
                            Id = "5c877d72-b7b7-44f2-97a9-69e15e633a5c",
                            Career = "Spa / Làm đẹp"
                        },
                        new
                        {
                            Id = "63338253-e36e-4ed6-81b8-2b1dcfc33d3e",
                            Career = "Tài chính / Đầu tư"
                        },
                        new
                        {
                            Id = "6e7ae9be-3f5f-4341-9d61-f1e22b7f46a8",
                            Career = "Thiết kế đồ họa"
                        },
                        new
                        {
                            Id = "ed1543a4-aed2-4610-96a3-bad51813470e",
                            Career = "Thiết kế nội thất"
                        },
                        new
                        {
                            Id = "b4489070-ab01-4dbd-80cd-ca5f5dcdbd5a",
                            Career = "Thời trang"
                        },
                        new
                        {
                            Id = "b678c0a5-4b81-4a50-901b-484c8f23c137",
                            Career = "Thư ký / Trợ lý"
                        },
                        new
                        {
                            Id = "4b058b33-3319-4471-8eaa-be1aa63b7105",
                            Career = "Thực phẩm / Đồ uống"
                        },
                        new
                        {
                            Id = "4ffa3906-28f1-42a6-a03f-40961507c903",
                            Career = "Tổ chức sự kiện / Quà tặng"
                        },
                        new
                        {
                            Id = "74779ffb-3551-49be-a8ab-651d43767dcb",
                            Career = "Tư vấn"
                        },
                        new
                        {
                            Id = "8deed0b2-7853-4c16-bbe1-a1aff2e9ee73",
                            Career = "Vận tải / Kho vận"
                        },
                        new
                        {
                            Id = "2b8d0563-e9b1-48cb-a42f-74b009554174",
                            Career = "Xây dựng"
                        },
                        new
                        {
                            Id = "b2058757-ed2a-4e2f-a3f7-8308a4041239",
                            Career = "Xuất nhập khẩu"
                        },
                        new
                        {
                            Id = "5dbcb5ee-d2d5-4f11-99c9-b1f18cc4b72f",
                            Career = "Y tế / Dược"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobField");

                    b.HasData(
                        new
                        {
                            Id = "86078f1a-b511-4c43-9b05-8cb92f8ee4f0",
                            Field = "Tất cả lĩnh vực"
                        },
                        new
                        {
                            Id = "c5d7a5d9-18ba-49b2-9089-b98d0fda2b5e",
                            Field = "Agency (Design/Development)"
                        },
                        new
                        {
                            Id = "111c0f1f-7ad3-469e-ad30-2fdfe5c874fd",
                            Field = "Agency (Marketing/Advertising)"
                        },
                        new
                        {
                            Id = "064e299c-b7b4-4530-9563-cb3bb7ce2419",
                            Field = "Bán lẻ - Hàng tiêu dùng - FMCG"
                        },
                        new
                        {
                            Id = "b22ec23c-75cf-4fe5-b311-a0b2ada685c1",
                            Field = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "5d85b25f-a1ba-4404-a02d-4b1252786886",
                            Field = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "c73e4680-0a2c-4894-80df-0e82cf6a260b",
                            Field = "Bất động sản"
                        },
                        new
                        {
                            Id = "d63944de-bc8f-4485-96c4-1a4e2419d19d",
                            Field = "Chứng khoán"
                        },
                        new
                        {
                            Id = "934aa481-56a1-4fd6-af2e-dada2e1c0334",
                            Field = "Cơ khí"
                        },
                        new
                        {
                            Id = "fe2a8f8e-8cf7-4438-ab48-0d32295f47f7",
                            Field = "Cơ quan nhà nước"
                        },
                        new
                        {
                            Id = "94557b78-91d2-43e6-9234-73fd580751f1",
                            Field = "Du lịch"
                        },
                        new
                        {
                            Id = "0b9d98fb-120b-4090-8cb9-af1f77dcb91b",
                            Field = "Dược phẩm / Y tế / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "0cc2abe5-ff22-42bb-9ca8-5578600bdc82",
                            Field = "Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "b82c5916-e502-4e30-89be-96f084df4cd0",
                            Field = "Giải trí"
                        },
                        new
                        {
                            Id = "cf73bb7b-7caf-41dc-9a62-a97054a01a29",
                            Field = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "dc0b5c68-1162-421e-8adc-e6fec67ee557",
                            Field = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "2fb68ac7-749b-42b2-81ec-576c3d7da881",
                            Field = "Internet / Online"
                        },
                        new
                        {
                            Id = "0fc31739-5ef9-4451-b261-a16307c18396",
                            Field = "IT - Phần cứng"
                        },
                        new
                        {
                            Id = "d0c3b88c-9018-4cb3-933f-53179aa1c50a",
                            Field = "IT - Phần mềm"
                        },
                        new
                        {
                            Id = "b60d225a-d2d0-4de5-994b-74576fc7e389",
                            Field = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "42909b36-71c6-4a69-b361-ef7d7afa442a",
                            Field = "Khác"
                        },
                        new
                        {
                            Id = "fcdedd8d-df55-44c7-b6a9-e16a1650c825",
                            Field = "Logistics - Vận tải"
                        },
                        new
                        {
                            Id = "7295fb79-1534-4ee9-bd42-720ea930098f",
                            Field = "Luật"
                        },
                        new
                        {
                            Id = "37ab6970-7ae1-4178-9607-cb42ac86e060",
                            Field = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "328cf12d-3c93-42fd-a9e9-17cb432e1b19",
                            Field = "Môi trường"
                        },
                        new
                        {
                            Id = "ccfffa10-0468-4d2e-9d20-574ddf8218a6",
                            Field = "Năng lượng"
                        },
                        new
                        {
                            Id = "8a08f83a-be20-4911-bb56-392f4689a492",
                            Field = "Ngân hàng"
                        },
                        new
                        {
                            Id = "8b1db17d-2bc2-4a30-999a-cfee742a8475",
                            Field = "Nhà hàng / Khách sạn"
                        },
                        new
                        {
                            Id = "b014bf24-9813-4ffb-afd0-b4d2d6d92637",
                            Field = "Nhân sự"
                        },
                        new
                        {
                            Id = "0ef93a62-1f09-40ed-b989-3b0e360a93ab",
                            Field = "Nông Lâm Ngư nghiệp"
                        },
                        new
                        {
                            Id = "ca48c348-c321-456c-af44-7a2485909b4b",
                            Field = "Sản xuất"
                        },
                        new
                        {
                            Id = "3d579e0c-f0e8-427b-b18a-e88b8de89cf6",
                            Field = "Tài chính"
                        },
                        new
                        {
                            Id = "dd63dd63-e394-4754-b491-de27d866f357",
                            Field = "Thiết kế / kiến trúc"
                        },
                        new
                        {
                            Id = "beb3540a-9f3d-4649-88e8-3e1a1ea1e537",
                            Field = "Thời trang"
                        },
                        new
                        {
                            Id = "e7446408-eafb-44bd-be7f-88ef13db2035",
                            Field = "Thương mại điện tử"
                        },
                        new
                        {
                            Id = "35340c9e-3258-4072-9c5b-890abb918fc7",
                            Field = "Tổ chức phi lợi nhuận"
                        },
                        new
                        {
                            Id = "939e70ed-9f79-4b6e-90c1-590762eb0ad2",
                            Field = "Tự động hóa"
                        },
                        new
                        {
                            Id = "c106cd84-b080-4c8b-b11a-25c8bbcb48a5",
                            Field = "Tư vấn"
                        },
                        new
                        {
                            Id = "b6f51316-a223-4c8b-ad3f-20596d2af9bb",
                            Field = "Viễn thông"
                        },
                        new
                        {
                            Id = "6d3cc748-9b6b-466c-a75e-3482740d8695",
                            Field = "Xây dựng"
                        },
                        new
                        {
                            Id = "44b9c4f6-98f3-46f7-b8d8-22e22bd0f4c9",
                            Field = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobForm");

                    b.HasData(
                        new
                        {
                            Id = "bd403036-e5d5-4386-828a-0e0eefe6d456",
                            Form = "Tất cả hình thức"
                        },
                        new
                        {
                            Id = "cf95f58a-b696-4a01-baaf-929072113719",
                            Form = "Toàn thời gian"
                        },
                        new
                        {
                            Id = "0e40697a-6f41-4235-8311-5dd14b628ef9",
                            Form = "Bán thời gian"
                        },
                        new
                        {
                            Id = "da7badd2-1ec7-4732-9e8a-0ca7ff5937ef",
                            Form = "Thực tập"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosition");

                    b.HasData(
                        new
                        {
                            Id = "f4f00204-5a8b-488e-9f0b-63061032e786",
                            Position = "Tất cả vị trí"
                        },
                        new
                        {
                            Id = "7f9aa195-f13c-4e13-a2e7-d7cfbbeb24c3",
                            Position = "Nhân viên"
                        },
                        new
                        {
                            Id = "f0d9da79-67ad-46f1-b443-80b75898846f",
                            Position = "Trưởng nhóm"
                        },
                        new
                        {
                            Id = "7031f11d-cd97-4183-be21-5db3751d2b6e",
                            Position = "Trưởng / Phó phòng"
                        },
                        new
                        {
                            Id = "e87ef7c0-2e67-4ebe-8aea-45f8e70049d1",
                            Position = "Quản lí / Giám sát"
                        },
                        new
                        {
                            Id = "37190f0d-c360-4039-b629-4b096fbc6057",
                            Position = "Trưởng chi nhánh"
                        },
                        new
                        {
                            Id = "8e8af423-0e0b-4b46-8207-6b18fc083dec",
                            Position = "Phó giám đốc"
                        },
                        new
                        {
                            Id = "f15b28bd-425f-4de4-9283-37a29bff4c94",
                            Position = "Giám đốc"
                        },
                        new
                        {
                            Id = "51035fce-71c9-42ff-9b80-9db27deeacb9",
                            Position = "Thực tập sinh"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecruitmentCVCurriculumVitaeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecruitmentCVRecruitmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RecruitmentCVRecruitmentId", "RecruitmentCVCurriculumVitaeId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = "b424bce3-7ac6-42f5-bf10-9d19b3bd2f42",
                            Name = "Tất cả tỉnh thành"
                        },
                        new
                        {
                            Id = "25eecf9e-96e1-43da-9fa4-b11ed715d1c4",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = "bfac00e8-526c-4053-9c16-0799e689bb97",
                            Name = "Bà Rịa-Vũng Tàu"
                        },
                        new
                        {
                            Id = "80265ede-48d5-47d9-8c39-0fa3cd740666",
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = "03fb78de-91db-41ec-b0dd-31e8edb54625",
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = "843b54a2-f157-4ea0-99b8-91aa5ac22554",
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = "1f0b167c-9d29-4884-8282-f64812ad4358",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = "f53f2081-4553-44a9-85c7-65c59b866c85",
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = "01205c4e-0f0f-4352-83f0-afc8efbbfb53",
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = "d1b40f42-3893-4fe7-8baf-8a1706a4e52f",
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = "791a78aa-1771-4905-9912-dc6c51f6c584",
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = "705f91da-0c45-49d0-957f-ac4174415e96",
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = "6c88ecfd-ee90-4bf9-86d2-8657b4d44122",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = "fc28f72f-b153-44c6-8b82-b19ce9a33e27",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = "bc6dfcea-123c-4f30-912c-c91e4496cc0d",
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = "5370a4af-f42f-4995-8b10-488a9e718932",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = "5d6a1a75-3903-407d-b58c-834dedb03ec0",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = "45620ffe-138b-4530-b1a9-56a03518d405",
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = "4ced0126-ce3f-4bc6-8b29-b15fcf8a5690",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = "b00eea49-8d40-4bfd-8242-c44041fde462",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = "19bdf49b-3998-41b1-bd8a-10e0ed6967fe",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = "326d84cb-46aa-41fa-b543-062253285486",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = "4408c821-878a-46c1-bd70-938810a8218f",
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = "3d8a6486-cbc9-464a-89c3-dad7fd6ff44c",
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = "f398027c-146d-405d-9897-64ca5a10d6e0",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = "cbb7c196-6a6e-45ce-a146-32ab7f60dbf4",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = "97604a88-a6f3-42dd-96f2-b1ff479be6fe",
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = "0a8f678d-7149-42f6-8e4e-4d03ea01900b",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = "a992a2ae-5607-4ae3-9ede-649105521de4",
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = "aefbf4dd-e302-4350-bfb9-b26bb8c4bede",
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = "bb62a093-d7cf-438a-9f39-5bce9a526b1f",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = "01e7c7b8-71ec-4d90-bfff-538d12321cd7",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = "56f617a5-594f-46d5-ab9f-0360647d071f",
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = "ae1ae957-d034-415c-90e9-58e170d5dc83",
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = "37355985-005e-4a37-a144-a1a0b154d353",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = "8341a199-5ed0-48c5-83b9-7f897daadcee",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = "3368ceb2-fa1d-4f37-ab75-1cebca98a7fa",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = "c91ccb53-4e3c-4e98-9c8f-f2ee8fae6cd9",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = "a28f4eb5-cfa9-48e8-adc0-06581b2f4d3f",
                            Name = "Long An"
                        },
                        new
                        {
                            Id = "11c7c0ed-28c5-4e9e-bab2-3cfaa0824dc6",
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = "461e80d9-4d66-43fa-af23-d3d43d560c3a",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = "f76ad461-1b3a-4436-90d7-42716b5484cd",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = "6b2b6298-288f-4cdf-87bc-da38532c32cc",
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = "76be2906-144f-4352-af53-4f762db42c83",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = "f505d3ae-a14d-473c-a751-1590bc1596e8",
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = "2cb3e3f4-1b43-4c31-9e5a-300f14693b82",
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = "52f3485c-aeae-4ffa-b63a-7d495530a0e2",
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = "d2868bb9-4dd0-45cb-b037-be1a34ccedb4",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = "8121fd2a-4e0e-4198-995a-cf36ffd9c5a9",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = "a5fcf9eb-5870-4895-8b70-35975da893cd",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = "a58b3b1b-7176-44fb-9ab2-f8247d677fb9",
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = "9c867fa4-fd8e-44fc-bd74-4bc33dd63c7f",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = "39f6464e-8628-48a8-b24a-c274eb9e3282",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = "af83d617-66af-400f-b35a-672f625e9203",
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = "8866c0b8-301d-4e5d-a322-b4c5e7d78ec8",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = "68f1b526-5489-47d9-8593-0bc082c88922",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = "49d771c0-6c5d-4ccd-9a93-3f7d220e63f4",
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = "96d9c7f4-b106-4d28-96e0-319f8c64b180",
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = "9653896f-cc7d-422b-959b-30cda4d02ea0",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = "f547711f-8cba-47a9-94d8-21d9d42198e7",
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = "43385ca2-14a3-4a8c-978f-b88413fb61fb",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = "453d4717-9ad6-4b3c-818f-a732c0318adb",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = "8574b4cb-e2b3-483b-a51b-338cefec66e7",
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = "164f48cd-c0c8-4fe8-b8c0-0a0a19b8a456",
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("JobAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobCareerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobFieldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobPositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("JobCareerId");

                    b.HasIndex("JobFieldId");

                    b.HasIndex("JobFormId");

                    b.HasIndex("JobPositionId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.Property<string>("RecruitmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurriculumVitaeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.HasKey("RecruitmentId", "CurriculumVitaeId");

                    b.HasIndex("CurriculumVitaeId");

                    b.ToTable("RecruitmentCV");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "c888e172-1c97-47bc-8fb8-d386adce710a",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "f8e1ec8e-54a8-4720-8f4a-7fe68d1de77c",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            Id = "576b50d6-a539-40a9-b6fa-1d030efcb642",
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "2f5ef746-7f88-47d8-8534-35fe1b30ecba",
                            Email = "cvlookup.sgu.2023@gmail.com",
                            Username = "General Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = "c888e172-1c97-47bc-8fb8-d386adce710a",
                            UserId = "2f5ef746-7f88-47d8-8534-35fe1b30ecba"
                        },
                        new
                        {
                            RoleId = "576b50d6-a539-40a9-b6fa-1d030efcb642",
                            UserId = "8b5e30c2-1c4e-40f5-b468-738c8a7cc4e1"
                        },
                        new
                        {
                            RoleId = "f8e1ec8e-54a8-4720-8f4a-7fe68d1de77c",
                            UserId = "ae178b22-9c1a-47b7-818b-db40326c770b"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Candidate", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Candidate");

                    b.HasData(
                        new
                        {
                            Id = "ae178b22-9c1a-47b7-818b-db40326c770b",
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            Username = "Candidate Admin",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Employer", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employer");

                    b.HasData(
                        new
                        {
                            Id = "8b5e30c2-1c4e-40f5-b468-738c8a7cc4e1",
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            Username = "Employer Admin",
                            Address = "Admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Notification", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.RecruitmentCV", "RecruitmentCV")
                        .WithMany()
                        .HasForeignKey("RecruitmentCVRecruitmentId", "RecruitmentCVCurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecruitmentCV");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId");

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobAddress", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobCareer", "JobCareer")
                        .WithMany()
                        .HasForeignKey("JobCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobField", "JobField")
                        .WithMany()
                        .HasForeignKey("JobFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobForm", "JobForm")
                        .WithMany()
                        .HasForeignKey("JobFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Experience");

                    b.Navigation("JobAddress");

                    b.Navigation("JobCareer");

                    b.Navigation("JobField");

                    b.Navigation("JobForm");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.CurriculumVitae", "CurriculumVitae")
                        .WithMany()
                        .HasForeignKey("CurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVitae");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
