// <auto-generated />
using System;
using FirstWebApi.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVLookup_WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Actived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "a981527a-18e8-44e2-b706-50e791d3d57e",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 16, 13, 31, 51, 140, DateTimeKind.Local).AddTicks(9525),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "27d3fa40-4c97-494c-96a4-deb449dc7196",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 16, 13, 31, 51, 140, DateTimeKind.Local).AddTicks(9542),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "860396b7-7408-4a1e-bbc1-0664637b9d98",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 16, 13, 31, 51, 140, DateTimeKind.Local).AddTicks(9546),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUser");

                    b.HasData(
                        new
                        {
                            AccountId = "a981527a-18e8-44e2-b706-50e791d3d57e",
                            UserId = "29c108ae-1271-474c-89d1-031ccf31996a"
                        },
                        new
                        {
                            AccountId = "27d3fa40-4c97-494c-96a4-deb449dc7196",
                            UserId = "42378e16-a0d0-4b9a-9c43-3b579a3a37ee"
                        },
                        new
                        {
                            AccountId = "860396b7-7408-4a1e-bbc1-0664637b9d98",
                            UserId = "6b02c9f2-ffe0-49c2-b031-729df89d9f70"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introdution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CurriculumVitae");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = "c09ac004-e77c-4405-b81b-3dd3789bd448",
                            Name = "Quận Ninh Kiều",
                            ProvinceId = "1e25842e-3daf-4c58-938b-70c59c7a95cf"
                        },
                        new
                        {
                            Id = "a44b6376-0ec8-499b-8afa-291fc6518882",
                            Name = "Quận Bình Thuỷ",
                            ProvinceId = "1e25842e-3daf-4c58-938b-70c59c7a95cf"
                        },
                        new
                        {
                            Id = "8f28bafb-4e64-47fe-9c94-1bb5ae7bd228",
                            Name = "Quận Cái Răng",
                            ProvinceId = "1e25842e-3daf-4c58-938b-70c59c7a95cf"
                        },
                        new
                        {
                            Id = "bbf75414-26de-439a-a272-6d503c9a5c68",
                            Name = "Quận Thốt Nốt",
                            ProvinceId = "1e25842e-3daf-4c58-938b-70c59c7a95cf"
                        },
                        new
                        {
                            Id = "6ff7fd5e-05ee-40c9-8218-1bfd54a90ba9",
                            Name = "Quận Ô Môn",
                            ProvinceId = "1e25842e-3daf-4c58-938b-70c59c7a95cf"
                        },
                        new
                        {
                            Id = "3ef375d2-25cf-4c4c-ac8a-cd1d662d954e",
                            Name = "Quận Liên Chiểu",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "539b8e98-3001-4978-9ca7-b56d1f580e2b",
                            Name = "Quận Thanh Khê",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "117516e9-c6a6-4212-920a-1b23f7616a9e",
                            Name = "Quận Hải Châu",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "1949ef3b-c26f-4c18-8067-7a9e321f6ba1",
                            Name = "Quận Sơn Trà",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "88c89473-ccb7-4819-8096-43105c614a50",
                            Name = "Quận Ngũ Hành Sơn",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "3f3de633-38d6-4164-8711-afc5249880b0",
                            Name = "Quận Cẩm Lệ",
                            ProvinceId = "18826909-c7d0-40b8-af88-fafcbe62d8a7"
                        },
                        new
                        {
                            Id = "7959c366-53d6-43fa-8103-be10242c47d2",
                            Name = "Quận Ba Đình",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "bee384dc-b2d5-4c28-9f75-ce10f66aa72d",
                            Name = "Quận Hoàn Kiếm",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "a6ae838c-8ca6-4968-99d8-72bbf0696fe6",
                            Name = "Quận Tây Hồ",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "4c806054-8a0d-49cf-85d8-b18148bc4957",
                            Name = "Quận Long Biên",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "96073f05-8267-41f6-beaa-e9a602ec706e",
                            Name = "Quận Cầu Giấy",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "d0c466a7-4418-4c84-a4ff-d4bd093fddef",
                            Name = "Quận Đống Đa",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "af6fdd82-328b-4b1b-b8d3-344834846e05",
                            Name = "Quận Hai Bà Trưng",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "0dbd6f24-5ec5-4318-a781-dafee81c4889",
                            Name = "Quận Hoàng Mai",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "02d94772-26fc-4bac-9e5a-f1fc29e4dabe",
                            Name = "Quận Thanh Xuân",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "5b18b95d-d1bb-4c04-9867-f4146b3e0e20",
                            Name = "Quận Nam Từ Liêm",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "29801f44-a357-4585-bc00-d5cb0b7c004c",
                            Name = "Quận Bắc Từ Liêm",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "b80bb867-fb60-4d0d-bac0-c95b4d506eec",
                            Name = "Quận Hà Đông",
                            ProvinceId = "bebf9951-0c1b-4725-bf08-d1cad3e823ff"
                        },
                        new
                        {
                            Id = "fa9fed9c-9fda-4420-93b9-3464d3c45abc",
                            Name = "Quận Hồng Bàng",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "83560725-d323-4067-b174-a49729f83b8d",
                            Name = "Quận Ngô Quyền",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "5d14502b-6c5d-4db0-930c-07a0d5748fcd",
                            Name = "Quận Lê Chân",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "876e8801-6d88-462f-8c4e-4782b3c509fe",
                            Name = "Quận Hải An",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "8e7333a6-3d61-48c9-99c4-ceabe0d292b2",
                            Name = "Quận Kiến An",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "65520b7f-2e24-42a9-a24d-8c117b477a27",
                            Name = "Quận Đồ Sơn",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "8497c800-73eb-47ed-951e-707f0e14ed64",
                            Name = "Quận Dương Kinh",
                            ProvinceId = "c4bea3ad-0789-4f06-8506-833e8f2bba02"
                        },
                        new
                        {
                            Id = "500d2ef8-a29e-42f2-81fb-6a4cafc56623",
                            Name = "Quận 1",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "1bbba632-e31f-4f62-b6a0-d6a80460c578",
                            Name = "Quận 2",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "e035a964-317a-40ec-9315-52f92b972c7c",
                            Name = "Quận 3",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "f4d35129-eb9f-4310-b6bb-8cad3a7d140e",
                            Name = "Quận 4",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "3c5957d3-33ef-4750-b9cc-add8209701a6",
                            Name = "Quận 5",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "d1dfcdcb-bd72-4a89-a9fd-a7c01aa0392d",
                            Name = "Quận 6",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "ebb75aad-1807-4bdd-bcee-8eeff532b26b",
                            Name = "Quận 7",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "255edfe8-7932-4412-9579-f83827c81ba4",
                            Name = "Quận 8",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "bc5981e6-f449-4d9c-ac21-9d903f6769b9",
                            Name = "Quận 9",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "d4247c1f-4b6c-43bc-8b3b-93b332363dd4",
                            Name = "Quận 10",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "4dd70607-4b2d-4eac-a140-54b5c10757d0",
                            Name = "Quận 11",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "4d5a73be-a0b1-426f-8e51-3c80c52ef520",
                            Name = "Quận 12",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "a7154b39-4cd9-41e2-a34e-41b965603182",
                            Name = "Quận Gò Vấp",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "68bdcad5-79f0-4592-961f-dc6feb0d3fa5",
                            Name = "Quận Bình Thạnh",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "a360554d-ad6b-45bf-9ad4-36fde99c99f7",
                            Name = "Quận Tân Bình",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "1c1fc154-d015-4ba4-8276-28210b62a93b",
                            Name = "Quận Tân Phú",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "79ef9a86-12a6-4216-b19b-45ac43887196",
                            Name = "Quận Phú Nhuận",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "3ad7e536-79a4-485c-b56f-9e47ce5b0fc9",
                            Name = "Quận Thủ Đức",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        },
                        new
                        {
                            Id = "9d7bf836-7d89-426c-bb01-7ec1ee987496",
                            Name = "Quận Bình Tân",
                            ProvinceId = "faa64fa8-0c21-4c45-ad6f-992903e77bcf"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = "e09351f6-7905-4c47-8c69-9fb34e3ad318",
                            Exp = "Tất cả kinh nghiệm"
                        },
                        new
                        {
                            Id = "168da662-6be1-4c92-b0e7-a83ccd6a3fbe",
                            Exp = "Chưa có kinh nghiệm"
                        },
                        new
                        {
                            Id = "9b622e39-e53c-473d-85c1-c2eae8713905",
                            Exp = "Dưới 1 năm"
                        },
                        new
                        {
                            Id = "506c8c00-a27b-45a1-a631-3a2a02b075d8",
                            Exp = "Từ 1-2 năm"
                        },
                        new
                        {
                            Id = "8013840d-fac3-4a8e-90ef-13db5784b822",
                            Exp = "Từ 2-3 năm"
                        },
                        new
                        {
                            Id = "325b22bf-9d91-4ae6-aaef-a4e8a2b5459a",
                            Exp = "Từ 3-5 năm"
                        },
                        new
                        {
                            Id = "3aa0debc-8fd7-459e-8a93-68ec5a9c3853",
                            Exp = "Từ 5-10 năm"
                        },
                        new
                        {
                            Id = "a8cac33f-eaa3-4a6a-b549-85f7f26f65a7",
                            Exp = "Trên 10 năm"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("JobAddress");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobCareer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCareer");

                    b.HasData(
                        new
                        {
                            Id = "332167a8-8aac-4bf2-8fb6-637190921a9e",
                            Career = "Tất cả ngành nghề"
                        },
                        new
                        {
                            Id = "a3158be0-2672-474d-b01a-9a381e56f99b",
                            Career = "An toàn lao động"
                        },
                        new
                        {
                            Id = "650d2b11-095e-4528-9384-19132ac2f426",
                            Career = "Bán hàng kỹ thuật"
                        },
                        new
                        {
                            Id = "1dce8a6d-46c6-4f09-8432-bf33b6640473",
                            Career = "Bán lẻ / bán sỉ"
                        },
                        new
                        {
                            Id = "5d2eaa3b-a2aa-4b36-870e-38ecbf50f79e",
                            Career = "Báo chí / Truyền hình"
                        },
                        new
                        {
                            Id = "7d34c75e-4894-4ed8-94d3-9e8ee48b13bd",
                            Career = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "e08be9e6-28c6-4bbe-bc41-fa046753b44a",
                            Career = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "e9c7c558-c8b2-49c3-98a2-24a1f0bd8cef",
                            Career = "Bất động sản"
                        },
                        new
                        {
                            Id = "85f83688-7a33-46ce-ad68-a7438ba84185",
                            Career = "Biên / Phiên dịch"
                        },
                        new
                        {
                            Id = "0656e5be-f73e-425b-afcf-29b3d8105d81",
                            Career = "Bưu chính - Viễn thông"
                        },
                        new
                        {
                            Id = "60bb8af3-cf57-407b-905b-4538ae38e725",
                            Career = "Chứng khoán / Vàng / Ngoại tệ"
                        },
                        new
                        {
                            Id = "a5809c62-43f1-451f-a8ae-945b00511581",
                            Career = "Cơ khí / Chế tạo / Tự động hóa"
                        },
                        new
                        {
                            Id = "02a2eb3f-ce8a-437e-b3e2-aa39a3887f63",
                            Career = "Công nghệ cao"
                        },
                        new
                        {
                            Id = "2b353597-2f2d-4c9f-9152-605b1b02bdaa",
                            Career = "Công nghệ Ô tô"
                        },
                        new
                        {
                            Id = "b2846af9-f300-489a-bb06-cb298528bca1",
                            Career = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = "3e629a47-5998-4083-a5e0-cf4d602d0f5a",
                            Career = "Dầu khí/Hóa chất"
                        },
                        new
                        {
                            Id = "ccafa480-b012-4795-a7b3-287c6240025d",
                            Career = "Dệt may / Da giày"
                        },
                        new
                        {
                            Id = "22b545c0-2a38-4a92-ad70-465a2d1ee39d",
                            Career = "Địa chất / Khoáng sản"
                        },
                        new
                        {
                            Id = "35872ecc-fc8a-4265-8118-702a70536e87",
                            Career = "Dịch vụ khách hàng"
                        },
                        new
                        {
                            Id = "727873e6-5b3f-4329-81af-a7926cce850b",
                            Career = "Điện / Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "c740058e-b84d-456b-bbcf-30fdb71c55ec",
                            Career = "Điện tử viễn thông"
                        },
                        new
                        {
                            Id = "98c18d3d-051d-48e1-909f-4d3d78847764",
                            Career = "Du lịch"
                        },
                        new
                        {
                            Id = "4df59eea-d64e-4f71-858d-4b77e5e236c7",
                            Career = "Dược phẩm / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "88fe6423-5dcd-485a-834f-fe7932748af7",
                            Career = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "2637c782-e2b6-4bab-a83a-5d2a5cfe37bd",
                            Career = "Hàng cao cấp"
                        },
                        new
                        {
                            Id = "72599559-93c1-4da0-8546-dddc76fb7666",
                            Career = "Hàng gia dụng"
                        },
                        new
                        {
                            Id = "b0de1f71-a56d-4172-b7c7-c2739d255828",
                            Career = "Hàng hải"
                        },
                        new
                        {
                            Id = "b5a60026-49ef-4921-8fd4-c968871b23a4",
                            Career = "Hàng không"
                        },
                        new
                        {
                            Id = "4802c494-c5d8-4db5-81bf-0bd87bd58d19",
                            Career = "Hàng tiêu dùng"
                        },
                        new
                        {
                            Id = "5959cb9c-a842-460e-ab8f-d251aab66cb1",
                            Career = "Hành chính / Văn phòng"
                        },
                        new
                        {
                            Id = "6425d304-6d51-4567-8ded-00275b256c80",
                            Career = "Hoá học / Sinh học"
                        },
                        new
                        {
                            Id = "ce8dfd09-24d9-4f85-81b7-86d3350a6d0d",
                            Career = "Hoạch định / Dự án"
                        },
                        new
                        {
                            Id = "1ac80cfa-6f9e-4a7f-b411-14061343c759",
                            Career = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "3654b47e-ea7f-4df6-9166-fadbaeff4e56",
                            Career = "IT Phần cứng / Mạng"
                        },
                        new
                        {
                            Id = "e11b5945-527b-433f-a585-268e1646b23d",
                            Career = "IT phần mềm"
                        },
                        new
                        {
                            Id = "88d3fa31-a95c-47a3-87a6-b2853c0f76bd",
                            Career = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "c3bca579-25e8-40d9-a061-f64c52b2f026",
                            Career = "Khách sạn / Nhà hàng"
                        },
                        new
                        {
                            Id = "9f0906fd-e3a8-4672-bbf2-0dbc38573d88",
                            Career = "Kiến trúc"
                        },
                        new
                        {
                            Id = "3198d0ae-6f3c-4ccc-b9e1-76e99317c7b2",
                            Career = "Kinh doanh / Bán hàng"
                        },
                        new
                        {
                            Id = "ded84f73-1138-40ae-88b9-a96d80e1221e",
                            Career = "Logistics"
                        },
                        new
                        {
                            Id = "785d6e96-416c-4cd7-9bd9-625cb11ca511",
                            Career = "Luật / Pháp lý"
                        },
                        new
                        {
                            Id = "ba6643be-ea2f-4683-a352-dba220ba9fc4",
                            Career = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "03e0da5a-f922-4c2f-b875-be53f5b5c0ac",
                            Career = "Môi trường / Xử lý chất thải"
                        },
                        new
                        {
                            Id = "5460d4ac-338d-4ace-a774-0c0b4493e270",
                            Career = "Mỹ phẩm / Trang sức"
                        },
                        new
                        {
                            Id = "6185d3eb-a0ee-438e-a6a5-a27d1d1b6a38",
                            Career = "Mỹ thuật / Nghệ thuật / Điện ảnh"
                        },
                        new
                        {
                            Id = "109e10bb-a0a2-4972-8903-974ae9893460",
                            Career = "Ngân hàng / Tài chính"
                        },
                        new
                        {
                            Id = "0c2a375a-dd79-45d5-b666-7db222c07fac",
                            Career = "Ngành nghề khác"
                        },
                        new
                        {
                            Id = "f9928e29-a774-4f54-b288-78567dbe71ed",
                            Career = "NGO / Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "5695dfb0-7297-4027-aa20-a8477cc39196",
                            Career = "Nhân sự"
                        },
                        new
                        {
                            Id = "2ea41de9-dcab-4dd0-84ef-324c135af985",
                            Career = "Nông / Lâm / Ngư nghiệp"
                        },
                        new
                        {
                            Id = "cb1a709e-ff3c-4ae2-ae05-d8acbc3b6413",
                            Career = "Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "578ab4b9-25e8-4790-ad97-29bdff6bd3de",
                            Career = "Quản lý chất lượng (QA/QC)"
                        },
                        new
                        {
                            Id = "157de650-a1d9-45c3-97bd-58eab9e13a38",
                            Career = "Quản lý điều hành"
                        },
                        new
                        {
                            Id = "8809a94c-c8f6-45f3-8915-cacf9785ba9d",
                            Career = "Sản phẩm công nghiệp"
                        },
                        new
                        {
                            Id = "5102b990-4b47-4562-85ea-75fe9c5c74de",
                            Career = "Sản xuất"
                        },
                        new
                        {
                            Id = "2d87574b-71b0-4cb0-aa1c-432f37745acd",
                            Career = "Spa / Làm đẹp"
                        },
                        new
                        {
                            Id = "43dc9226-d110-47a7-8039-9e5c0694dbfd",
                            Career = "Tài chính / Đầu tư"
                        },
                        new
                        {
                            Id = "872259e6-76af-4175-8409-20d7850ed4fd",
                            Career = "Thiết kế đồ họa"
                        },
                        new
                        {
                            Id = "a79cf28e-83ab-410e-8c09-4d5eba766e40",
                            Career = "Thiết kế nội thất"
                        },
                        new
                        {
                            Id = "6968f64e-ca6e-4128-936a-f7bc10b5817f",
                            Career = "Thời trang"
                        },
                        new
                        {
                            Id = "0543978f-676d-41e0-8b82-e7ddfc2dcbec",
                            Career = "Thư ký / Trợ lý"
                        },
                        new
                        {
                            Id = "22511cf5-6f3e-4470-8f12-61b0fa164653",
                            Career = "Thực phẩm / Đồ uống"
                        },
                        new
                        {
                            Id = "a41485bb-7a1e-4f75-b159-9dda6e84b3dc",
                            Career = "Tổ chức sự kiện / Quà tặng"
                        },
                        new
                        {
                            Id = "8253818d-a8dd-4d1f-aa55-ba598d6f4d7b",
                            Career = "Tư vấn"
                        },
                        new
                        {
                            Id = "ffc17928-a334-4813-9575-6e3c8f109aff",
                            Career = "Vận tải / Kho vận"
                        },
                        new
                        {
                            Id = "1fd87f96-5a56-481b-9eeb-a31df3dee791",
                            Career = "Xây dựng"
                        },
                        new
                        {
                            Id = "0e2b45d8-03a8-48b8-87bb-cea86a72f350",
                            Career = "Xuất nhập khẩu"
                        },
                        new
                        {
                            Id = "23090cd6-2c64-4afc-b8bc-d7b4cff04ab6",
                            Career = "Y tế / Dược"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobField");

                    b.HasData(
                        new
                        {
                            Id = "9d479fc0-5738-4034-aadb-058ac32540d2",
                            Field = "Tất cả lĩnh vực"
                        },
                        new
                        {
                            Id = "0633fdfb-a8ad-4fdf-ac36-47a66392a13c",
                            Field = "Agency (Design/Development)"
                        },
                        new
                        {
                            Id = "c10e21de-aa4c-4662-9e04-8ba5aebdeac3",
                            Field = "Agency (Marketing/Advertising)"
                        },
                        new
                        {
                            Id = "a1c3fe92-cac6-4160-b4c3-829aabed300b",
                            Field = "Bán lẻ - Hàng tiêu dùng - FMCG"
                        },
                        new
                        {
                            Id = "4c5b0b27-5bf4-4bd5-866c-6e81b993d9c2",
                            Field = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "c593cc87-a91e-40b6-9600-0f1f84eca096",
                            Field = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "708c062a-e3e5-4bef-817d-5d2f8c75e9e9",
                            Field = "Bất động sản"
                        },
                        new
                        {
                            Id = "82f44d6e-2ad2-4289-b868-eeda726c2ee4",
                            Field = "Chứng khoán"
                        },
                        new
                        {
                            Id = "40583791-e53b-4fcd-ad0b-550ece0c18d1",
                            Field = "Cơ khí"
                        },
                        new
                        {
                            Id = "c39f911f-dbc0-4879-820c-01aebb3d8065",
                            Field = "Cơ quan nhà nước"
                        },
                        new
                        {
                            Id = "38456503-d457-4ca1-a689-8078597ad5ed",
                            Field = "Du lịch"
                        },
                        new
                        {
                            Id = "7fca777e-1b89-436b-bc4b-6d891e735059",
                            Field = "Dược phẩm / Y tế / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "b27d7965-ebc8-415e-b9fb-f21a1b30d2ec",
                            Field = "Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "2f2f14e1-8e41-4144-b5f2-6e30bab70629",
                            Field = "Giải trí"
                        },
                        new
                        {
                            Id = "0e49577b-b053-48ee-959d-95365e887b06",
                            Field = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "70f4c606-17ba-40dd-9d97-c8c94d552776",
                            Field = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "fb431332-bf92-41b4-85d6-e0e9dc301bcf",
                            Field = "Internet / Online"
                        },
                        new
                        {
                            Id = "c9ef25f7-bcb3-4898-9fc8-0df816552e06",
                            Field = "IT - Phần cứng"
                        },
                        new
                        {
                            Id = "a11c33cc-eee7-4779-b8bb-7075e2c684d4",
                            Field = "IT - Phần mềm"
                        },
                        new
                        {
                            Id = "4b8fcf4e-66a6-4396-b406-c4541ff1e59e",
                            Field = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "82c3371b-8a78-4a67-8fd1-c24e82153d46",
                            Field = "Khác"
                        },
                        new
                        {
                            Id = "30ba9d9d-13a8-4788-ba73-317ab1d6ffc3",
                            Field = "Logistics - Vận tải"
                        },
                        new
                        {
                            Id = "76535fb0-8bb2-4a1d-a438-95e508e00aa7",
                            Field = "Luật"
                        },
                        new
                        {
                            Id = "e94e9f0f-99cc-43c4-8edc-8fbfc1f8cc7b",
                            Field = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "a626d8a2-79f7-46d2-808c-09ed29275ef0",
                            Field = "Môi trường"
                        },
                        new
                        {
                            Id = "ac8a8cf8-cac9-4f01-a420-15f91760d7b1",
                            Field = "Năng lượng"
                        },
                        new
                        {
                            Id = "4bc3ed6f-0d98-47ba-8c37-3b9fe43f311d",
                            Field = "Ngân hàng"
                        },
                        new
                        {
                            Id = "7a4db5ea-fa22-4912-9634-e36f08b803dc",
                            Field = "Nhà hàng / Khách sạn"
                        },
                        new
                        {
                            Id = "376556af-c709-4e07-977f-704b3b2a5b25",
                            Field = "Nhân sự"
                        },
                        new
                        {
                            Id = "7a7352af-7f40-496f-90cd-cb493faced41",
                            Field = "Nông Lâm Ngư nghiệp"
                        },
                        new
                        {
                            Id = "15ab0b08-9e57-4b2f-8d06-60cdf1689e1f",
                            Field = "Sản xuất"
                        },
                        new
                        {
                            Id = "9944ad83-5c00-47cc-a18e-98edf518d50d",
                            Field = "Tài chính"
                        },
                        new
                        {
                            Id = "3b544eaf-c75e-4deb-be5b-1834dcb62b25",
                            Field = "Thiết kế / kiến trúc"
                        },
                        new
                        {
                            Id = "82a65ed1-bf47-42d5-8c43-0cb9352d784f",
                            Field = "Thời trang"
                        },
                        new
                        {
                            Id = "901b0b65-32bd-4d67-8646-c9495675ce7b",
                            Field = "Thương mại điện tử"
                        },
                        new
                        {
                            Id = "4a3c1bd6-ad59-49d3-9fbd-343d995735c0",
                            Field = "Tổ chức phi lợi nhuận"
                        },
                        new
                        {
                            Id = "b8951758-21e2-434e-8c2c-dfe53b3a80eb",
                            Field = "Tự động hóa"
                        },
                        new
                        {
                            Id = "0b8ece97-d240-49e7-bcf6-939b6c7b07f1",
                            Field = "Tư vấn"
                        },
                        new
                        {
                            Id = "ce65b302-6f4d-4f19-a23c-60cacf9ff56b",
                            Field = "Viễn thông"
                        },
                        new
                        {
                            Id = "25c8d8e6-5bc6-465e-b6fd-beadf779b325",
                            Field = "Xây dựng"
                        },
                        new
                        {
                            Id = "5f78ea97-f503-47fc-bd8d-f54e38acb3e7",
                            Field = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobForm");

                    b.HasData(
                        new
                        {
                            Id = "2a59304c-74d6-4f5d-a941-40e0cfa71d8a",
                            Form = "Tất cả hình thức"
                        },
                        new
                        {
                            Id = "754260db-0a5d-40b5-aba0-113ab81019fb",
                            Form = "Toàn thời gian"
                        },
                        new
                        {
                            Id = "b4b041c8-74e3-43e0-90cc-7a46a2ba5612",
                            Form = "Bán thời gian"
                        },
                        new
                        {
                            Id = "c0c1c0d4-0f4d-4fb3-87ab-0f2c36538865",
                            Form = "Thực tập"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosition");

                    b.HasData(
                        new
                        {
                            Id = "ff988c93-70cf-43d4-997c-0d137daed7b1",
                            Position = "Tất cả vị trí"
                        },
                        new
                        {
                            Id = "4cfa71e9-10b5-47bd-a4cb-2f070dfe3671",
                            Position = "Nhân viên"
                        },
                        new
                        {
                            Id = "d108460c-28b9-4113-aa12-7fb4d2a61ed8",
                            Position = "Trưởng nhóm"
                        },
                        new
                        {
                            Id = "7153d5bd-cd98-4a1f-950f-0e5247d88766",
                            Position = "Trưởng / Phó phòng"
                        },
                        new
                        {
                            Id = "aafac5e2-ae42-47b4-9ccf-9b04ba3e7d92",
                            Position = "Quản lí / Giám sát"
                        },
                        new
                        {
                            Id = "b526c426-fdce-4f00-97d7-6adfaff2bbfd",
                            Position = "Trưởng chi nhánh"
                        },
                        new
                        {
                            Id = "9eb8c3ac-7109-4d74-b8e3-4e221605251d",
                            Position = "Phó giám đốc"
                        },
                        new
                        {
                            Id = "97505fe0-77ab-41fc-981c-b10b38756b42",
                            Position = "Giám đốc"
                        },
                        new
                        {
                            Id = "e83ae10f-29b1-4128-bc39-72c90be27d2c",
                            Position = "Thực tập sinh"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = "85395af3-61a1-4c17-aea0-044e6c01d774",
                            Name = "Tất cả tỉnh thành"
                        },
                        new
                        {
                            Id = "ac8fd5d1-81f9-4f96-ac50-9bb02b0bd153",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = "cd27c9cc-f724-445f-845c-3eb75dfcb888",
                            Name = "Bà Rịa-Vũng Tàu"
                        },
                        new
                        {
                            Id = "430940c7-145d-4d5a-9a53-9a5896257414",
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = "5d51e8f5-360b-420c-846f-2dcf81b6c8ad",
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = "593843d6-d1c3-423f-936a-665b9cc8986a",
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = "ba487765-4ecf-47bb-b5be-cb00fbab0c49",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = "2d6d1ab8-4406-41c5-83aa-d91495dc5581",
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = "be659505-2ce8-4294-a921-2fe1195775e4",
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = "ce95660c-c3c0-42f0-93b2-6fb2482f992a",
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = "883ca377-a18f-405d-a0f7-c222fde6f416",
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = "e917992e-78b8-4837-a082-4d3a74353749",
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = "adf54e57-75c4-41d8-9597-c71dd122c5c1",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = "1e25842e-3daf-4c58-938b-70c59c7a95cf",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = "930bd779-1067-4990-b855-764fd185b40f",
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = "18826909-c7d0-40b8-af88-fafcbe62d8a7",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = "dbbcd40c-3a95-425d-99ee-627959d5d882",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = "27a7bb15-d3a0-4179-902c-cf6c5c342f4b",
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = "8d135e1a-109e-4abe-85f9-88f4fa8a0f80",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = "654cf607-32e3-482d-a1eb-2624ad4a5477",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = "5d6e5fa5-d210-4148-addd-aadaed85889a",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = "4d12d10f-afaa-4e5d-bf18-c9672a230911",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = "b21a7b59-1e07-404e-b41e-5a4c5fdcc3d8",
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = "912e3bf3-a168-48bd-8eb0-c4817f573299",
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = "bebf9951-0c1b-4725-bf08-d1cad3e823ff",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = "aa992905-a486-4adc-9659-a8e9b570566f",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = "e70dcf96-b484-4ba2-a97d-1e9590da66b5",
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = "c4bea3ad-0789-4f06-8506-833e8f2bba02",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = "153202e4-da4a-4765-bbf4-cfec9ac80552",
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = "7828bcb3-481d-495d-8a89-76526b858822",
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = "628e5774-fc5b-459e-acb0-c201a4ac4a90",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = "b9bf19d9-22c9-48a7-a668-26ad91fc377c",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = "6f37bbb9-0665-4480-9043-56cc2e77b9e4",
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = "cf867e9b-1788-4d6a-87e1-0f2b0d9a3631",
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = "62a7fd10-dc8d-443f-bf50-c48cfa634803",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = "12566ac5-a437-4d5b-bd19-82b1fa340d6a",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = "535cb037-2bf5-408a-b0c7-e0d6eb36e7c5",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = "b9d5675a-8496-465a-959f-089d26122fcd",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = "bdd0a777-9356-4a84-bd74-3798f9bb0d53",
                            Name = "Long An"
                        },
                        new
                        {
                            Id = "6daa2422-5846-4414-87a0-8ff273364a72",
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = "125824ac-8e0f-49ac-81db-8096b858fae5",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = "dce3a4e3-1a45-4c87-9512-04aedf121761",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = "9eec4dcc-9e5a-452a-8433-ec3b34f97a74",
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = "c641cbb5-3aca-4ebd-8e76-adc6cb50a27c",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = "d7226e2e-b4ba-4b53-932d-22dabe5da728",
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = "eeca78e0-2cc5-410a-844d-76ecf61150be",
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = "cba9cb5e-7030-49a8-8121-2b25e1d65530",
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = "d2dd20be-d4a0-441b-9d99-3c02509e0d25",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = "1271d716-1bea-4831-979a-146711e8d8cd",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = "23cc6a54-3d5f-4907-bcc6-484f29c28e3d",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = "dfb54d30-139d-4e65-9257-1b31279b62d8",
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = "b5cd2d11-0947-4b9e-9661-9451eb343f2b",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = "3cd07990-e369-4e8f-872e-27dbd1f1151f",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = "39338aa4-4466-4dec-8ed0-179a95f8ff2d",
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = "69233b21-61fc-4294-b1a1-4a7079e80a22",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = "15d8827a-a89c-435b-95e3-4df34455e46b",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = "9eaad3a1-103b-48c0-bfcb-8ca79d7d67f8",
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = "873a1432-7633-4604-90ee-5d66450077de",
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = "faa64fa8-0c21-4c45-ad6f-992903e77bcf",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = "8c1ccc71-8bd7-4155-bb2e-7289a0a84a0f",
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = "891ec562-6a82-45ff-9ccd-d48aea820b63",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = "d0bcc803-3408-40d7-a044-6ef681d4828d",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = "fd2204bb-7d88-4b19-980b-a6eee9914b12",
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = "f3595c6b-f69f-49fd-a740-e5bca9a60ac9",
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("JobAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobCareerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobFieldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobPositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("JobCareerId");

                    b.HasIndex("JobFieldId");

                    b.HasIndex("JobFormId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.Property<string>("RecruitmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurriculumVitaeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecruitmentId", "CurriculumVitaeId");

                    b.HasIndex("CurriculumVitaeId");

                    b.ToTable("RecruitmentCV");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "2b79c358-3955-4afb-aa42-8a488e6b0fba",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "6b8fb1a4-e8e0-48c3-9c44-c9f169acc14f",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            Id = "2758164a-5435-4201-bed6-cf5eff9713ba",
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "29c108ae-1271-474c-89d1-031ccf31996a",
                            Email = "cvlookup.sgu.2023@gmail.com",
                            Username = "General Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = "2b79c358-3955-4afb-aa42-8a488e6b0fba",
                            UserId = "29c108ae-1271-474c-89d1-031ccf31996a"
                        },
                        new
                        {
                            RoleId = "2758164a-5435-4201-bed6-cf5eff9713ba",
                            UserId = "42378e16-a0d0-4b9a-9c43-3b579a3a37ee"
                        },
                        new
                        {
                            RoleId = "6b8fb1a4-e8e0-48c3-9c44-c9f169acc14f",
                            UserId = "6b02c9f2-ffe0-49c2-b031-729df89d9f70"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Candidate", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Candidate");

                    b.HasData(
                        new
                        {
                            Id = "6b02c9f2-ffe0-49c2-b031-729df89d9f70",
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            Username = "Candidate Admin",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Employer", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employer");

                    b.HasData(
                        new
                        {
                            Id = "42378e16-a0d0-4b9a-9c43-3b579a3a37ee",
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            Username = "Employer Admin",
                            Address = "Admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobAddress", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobCareer", "JobCareer")
                        .WithMany()
                        .HasForeignKey("JobCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobField", "JobField")
                        .WithMany()
                        .HasForeignKey("JobFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobForm", "JobForm")
                        .WithMany()
                        .HasForeignKey("JobFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Experience");

                    b.Navigation("JobAddress");

                    b.Navigation("JobCareer");

                    b.Navigation("JobField");

                    b.Navigation("JobForm");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.CurriculumVitae", "CurriculumVitae")
                        .WithMany()
                        .HasForeignKey("CurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVitae");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
