// <auto-generated />
using System;
using FirstWebApi.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVLookup_WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Actived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "a0f8ae06-2015-483f-a965-bae8076cdc5b",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023@gmail.com",
                            IssuedAt = new DateTime(2023, 10, 9, 16, 20, 17, 489, DateTimeKind.Local).AddTicks(7426),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUser");

                    b.HasData(
                        new
                        {
                            AccountId = "a0f8ae06-2015-483f-a965-bae8076cdc5b",
                            UserId = "f00739eb-9e82-4c73-bea4-4c54f14f2832"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introdution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CurriculumVitae");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = "23bdf9dd-627f-417d-b3f1-b24fef07131d",
                            Name = "Quận Ninh Kiều",
                            ProvinceId = "a1cd2457-ae55-463b-a0e3-302e6633246a"
                        },
                        new
                        {
                            Id = "e2760e77-3d84-435f-8ab9-268fc7103dd0",
                            Name = "Quận Bình Thuỷ",
                            ProvinceId = "a1cd2457-ae55-463b-a0e3-302e6633246a"
                        },
                        new
                        {
                            Id = "8da8826a-6ec1-48e4-aa21-b96ba23eab47",
                            Name = "Quận Cái Răng",
                            ProvinceId = "a1cd2457-ae55-463b-a0e3-302e6633246a"
                        },
                        new
                        {
                            Id = "8cf1aaa8-8ad4-4e05-ae6c-4e6e33b956e0",
                            Name = "Quận Thốt Nốt",
                            ProvinceId = "a1cd2457-ae55-463b-a0e3-302e6633246a"
                        },
                        new
                        {
                            Id = "f683b092-0766-4dd2-be3f-a5ee4238faa2",
                            Name = "Quận Ô Môn",
                            ProvinceId = "a1cd2457-ae55-463b-a0e3-302e6633246a"
                        },
                        new
                        {
                            Id = "e83eee76-96bc-4d44-a3a0-f545a4c2d5e4",
                            Name = "Quận Liên Chiểu",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "925645de-bb3b-47c3-8026-2ef2d17db58f",
                            Name = "Quận Thanh Khê",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "fee405d3-29b7-48b3-b061-326c010cfaf9",
                            Name = "Quận Hải Châu",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "97ab1b11-1393-45fd-87f3-e8a27724af01",
                            Name = "Quận Sơn Trà",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "11a31e5f-1e19-474a-badf-7b1f5915a23e",
                            Name = "Quận Ngũ Hành Sơn",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "0ff370af-7401-48f5-8a0e-69749c73d827",
                            Name = "Quận Cẩm Lệ",
                            ProvinceId = "b0416280-ccd5-41c7-9c92-766352985bf3"
                        },
                        new
                        {
                            Id = "75554002-6396-41a9-881d-72fe593ab1e0",
                            Name = "Quận Ba Đình",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "47a65f7c-bee4-439b-805f-e7b1c3020ae2",
                            Name = "Quận Hoàn Kiếm",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "060b5f05-bc79-44aa-8bbd-d9a99414ab05",
                            Name = "Quận Tây Hồ",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "2acc3a27-1d41-4811-9fa0-80262b4a508b",
                            Name = "Quận Long Biên",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "a60171e3-5f7a-4245-84ce-b10d85223992",
                            Name = "Quận Cầu Giấy",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "401c4ede-60e6-4a52-b879-804747d144fe",
                            Name = "Quận Đống Đa",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "e554d438-7c8d-405a-aadb-0bfed9d2b261",
                            Name = "Quận Hai Bà Trưng",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "ab1e18d7-9ef1-458a-a857-b6dd432bf577",
                            Name = "Quận Hoàng Mai",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "b752ed59-862c-4475-9180-fcdc5bbace7c",
                            Name = "Quận Thanh Xuân",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "027a1137-d53c-42b5-bf79-0c266e09e44d",
                            Name = "Quận Nam Từ Liêm",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "7585e982-3eae-4ab7-8bed-305af00f3be2",
                            Name = "Quận Bắc Từ Liêm",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "ffcfd0a0-67cb-4314-baa2-3178eb8e08a7",
                            Name = "Quận Hà Đông",
                            ProvinceId = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a"
                        },
                        new
                        {
                            Id = "12e39fee-ef45-4b12-879a-513761d0b5ca",
                            Name = "Quận Hồng Bàng",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "a35b11ed-06c0-47ed-af91-169d111fc755",
                            Name = "Quận Ngô Quyền",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "4c3a1e5e-e2b9-40a7-a396-5716880a2510",
                            Name = "Quận Lê Chân",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "546c4fa6-b622-411d-a62e-0d2444da25ee",
                            Name = "Quận Hải An",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "227d4752-9473-41a4-bc36-793406e09f67",
                            Name = "Quận Kiến An",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "10e1c3d4-0b27-4820-8f44-9a494fc8ef12",
                            Name = "Quận Đồ Sơn",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "17eef594-a5ad-413c-a331-4679d9f5eff0",
                            Name = "Quận Dương Kinh",
                            ProvinceId = "b646ee01-3baf-46b7-beba-b81862ff8043"
                        },
                        new
                        {
                            Id = "d4760497-b8a6-435d-9227-dfaf1f5758ad",
                            Name = "Quận 1",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "0802a493-a047-447f-9b18-185cb9f6c446",
                            Name = "Quận 2",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "d79f3392-e23e-43f3-b379-a4bc849b9fe9",
                            Name = "Quận 3",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "50008f39-a70f-4e57-a872-d1a5c1880339",
                            Name = "Quận 4",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "c7bb94c9-0567-410c-9d21-95d9add85dde",
                            Name = "Quận 5",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "e6407102-aa20-44cb-8ba8-c110d644b3f1",
                            Name = "Quận 6",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "6a5a43fd-b697-4153-aa88-b7cde67474ed",
                            Name = "Quận 7",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "c96a5d09-86f2-416b-86aa-8dddd73cbd44",
                            Name = "Quận 8",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "1dcc213b-0f65-4c44-b82b-d7b2d294f65d",
                            Name = "Quận 9",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "c521e33f-9176-4f26-9d07-214ef85ecbcb",
                            Name = "Quận 10",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "f53805b8-d749-4fbc-ada2-8d7423e37b89",
                            Name = "Quận 11",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "b5208ce7-cecb-469d-9c69-8830d30fd097",
                            Name = "Quận 12",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "d4212941-eee4-4430-a3ac-75c1a9090902",
                            Name = "Quận Gò Vấp",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "3fd9f224-c0b0-4371-aaaf-81e15f3d035a",
                            Name = "Quận Bình Thạnh",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "05868934-4128-484f-82cd-4c3c4a422122",
                            Name = "Quận Tân Bình",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "100f24ae-eb8f-4dcb-b53e-9f229fe13982",
                            Name = "Quận Tân Phú",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "09f9764b-0933-401c-bcfc-3cf82952330b",
                            Name = "Quận Phú Nhuận",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "57549019-6278-445c-b5a8-48a9c23deafb",
                            Name = "Quận Thủ Đức",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        },
                        new
                        {
                            Id = "df26399f-45a6-46c0-ac7b-dcf69a75fa20",
                            Name = "Quận Bình Tân",
                            ProvinceId = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("JobAddress");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobCareer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCareer");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobField");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobForm");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosition");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = "7fd6a237-f21b-4c69-b6fb-b6a5459e319c",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = "37449aae-cf7d-4fc5-85d2-15559b338df6",
                            Name = "Bà Rịa-Vũng Tàu"
                        },
                        new
                        {
                            Id = "9a2a06fb-6658-4279-a617-7ed95881b00c",
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = "76f3ce0c-4656-486d-8fe4-79ab54304122",
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = "d97f9507-4c77-4406-92c0-7598cce241ef",
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = "f18a6860-9ed5-419a-afac-488ab6154e05",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = "f1646799-d21a-490e-8388-d8d21bf00dfb",
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = "234a1897-fdef-485e-8d2e-f2129a860347",
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = "5ca5e764-4e7b-4a3a-8bde-b124b0cec69f",
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = "02a45a51-218a-4b4e-b385-dca7e6ed40bb",
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = "51f601cf-4bb0-46fe-9775-b81b3a1902d7",
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = "41afe4f1-b3a3-49e2-963f-9ec12d4de6a0",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = "a1cd2457-ae55-463b-a0e3-302e6633246a",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = "32f727cd-8de5-4a9c-a48a-b176296166e6",
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = "b0416280-ccd5-41c7-9c92-766352985bf3",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = "b552d3bd-ff04-4aa8-bb17-f47777da7df6",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = "ed77dd5b-df3b-40e0-8086-56adb1515cd5",
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = "522131f2-e6a5-4be6-b74d-90cbcbc8e4b1",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = "094e5d8d-094a-4c51-b96e-533a9f838f38",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = "f501ad4c-552e-4bf2-a21c-3a2a0d965a43",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = "fbc1bdc7-65e2-46ad-88be-39018603d9fd",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = "93fffbbe-e76f-4c25-b829-f90da5590bca",
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = "7cf4296c-4aef-4cf3-ae80-f1b533986e89",
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = "156bf526-c7fd-4f6c-85ed-3a00c06bac6a",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = "9264efcf-c8b8-4e68-a9db-55e46c92ae17",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = "c116ac20-93d9-474d-ba26-5a4ecf2fada0",
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = "b646ee01-3baf-46b7-beba-b81862ff8043",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = "5f728aa4-1d6e-4207-aeb4-fa6ae207e29a",
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = "5ede644e-9510-416f-922b-9104bdcaf5b2",
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = "c8913797-c162-4fba-8ffc-34d808f47135",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = "c26f3b28-3e54-46d3-b5f9-87e20128d6e1",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = "9b2f6139-db1e-420e-9e16-5797b56f1ac7",
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = "7a137f81-3b56-46f5-8ebd-d143d1db4bb6",
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = "44394de2-ec56-43ee-899b-c8fd6209fbe0",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = "5d0a7442-0a0e-44f2-9380-e8e67b49c73f",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = "9d27774b-9539-47c5-b974-02836234287a",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = "9b92f26d-6d19-4957-b571-9b761ca0d9fe",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = "a31c8358-626e-4a41-9bf0-c5a1e444161c",
                            Name = "Long An"
                        },
                        new
                        {
                            Id = "e1747a1e-0c11-492a-b209-f6e595f17fd3",
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = "c341b246-7999-4859-8c2e-75fd72dacbed",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = "c423b79a-eda3-4f94-9aad-2e624bf81f06",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = "40e66034-1153-4b9f-bbf7-0a50b15d6773",
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = "a01b6331-d3f9-46b5-bfc4-e8fc6a234999",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = "63b03b3f-8fbb-4549-876d-9e4263defa5d",
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = "866b6804-191f-462f-8f92-5d0b04b7d221",
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = "edad33c0-c7b6-42fd-9351-ba6983a64b43",
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = "e3a8d558-6f5e-455b-877b-8dfbd1aa6fcb",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = "ad9249fb-ad5c-43ea-b742-12ea91393081",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = "5f2aed7a-03bb-4516-8284-d627d085fef5",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = "9c739e24-0b8c-48ad-b0f7-ccef8618d0de",
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = "b6496e85-c61c-4ca9-8ab6-0a8fb13cc360",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = "46b30254-8722-4e4d-a796-3f710bbf03fd",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = "5d9b15db-1559-4c46-8479-121ae48af07c",
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = "2ab616c5-a907-4a71-a37b-9e6402213133",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = "10a9b650-8579-4f99-b475-4108e37bbf41",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = "b1d599d4-3f6f-4023-a482-ac04a442c6bb",
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = "1c7cd154-a48a-4182-af13-3369a0753cfd",
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = "6c5b10d1-0a87-4e87-8f66-bef01e2ae256",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = "c3897813-c729-49b1-bcdb-58f8627aa0f0",
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = "ceace927-454b-4eb5-badf-17b20959cc6a",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = "ed3e7f70-53ae-41b0-adb3-9539e1b0533e",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = "9ff82575-ed30-483e-a414-50f1c6424772",
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = "f7f0b01d-4490-4e78-9492-2fd1fccb3dc8",
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("JobAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobCareerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobFieldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobPositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("JobCareerId");

                    b.HasIndex("JobFieldId");

                    b.HasIndex("JobFormId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.Property<string>("RecruitmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurriculumVitaeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecruitmentId", "CurriculumVitaeId");

                    b.HasIndex("CurriculumVitaeId");

                    b.ToTable("RecruitmentCV");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "a0305f87-441d-482b-9f94-6192fadf48eb",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "01234fa9-5cde-43ba-be45-07429bfbee40",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            Id = "8877c75f-8aef-453c-847c-604eaff53e29",
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "f00739eb-9e82-4c73-bea4-4c54f14f2832",
                            Email = "cvlookup.sgu.2023@gmail.com"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = "a0305f87-441d-482b-9f94-6192fadf48eb",
                            UserId = "f00739eb-9e82-4c73-bea4-4c54f14f2832"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Candidate", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Candidate");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Employer", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employer");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobAddress", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobCareer", "JobCareer")
                        .WithMany()
                        .HasForeignKey("JobCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobField", "JobField")
                        .WithMany()
                        .HasForeignKey("JobFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobForm", "JobForm")
                        .WithMany()
                        .HasForeignKey("JobFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Experience");

                    b.Navigation("JobAddress");

                    b.Navigation("JobCareer");

                    b.Navigation("JobField");

                    b.Navigation("JobForm");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.CurriculumVitae", "CurriculumVitae")
                        .WithMany()
                        .HasForeignKey("CurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVitae");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
