// <auto-generated />
using System;
using FirstWebApi.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVLookup_WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Actived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "e75a027a-bfa8-430f-a3f0-82629734d6e8",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 6, 1, 16, 53, 615, DateTimeKind.Local).AddTicks(3262),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "ddad3b28-5a76-44fc-8a3f-ac3ad13da419",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 6, 1, 16, 53, 615, DateTimeKind.Local).AddTicks(3288),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "6b9a30fb-146c-47d7-af09-8b826212b329",
                            Actived = true,
                            ActivedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            IssuedAt = new DateTime(2023, 11, 6, 1, 16, 53, 615, DateTimeKind.Local).AddTicks(3301),
                            Password = "4EvS5r40usEAzXH5nw6YyjfVVpQdHt7K+e7DBWXhKPKdrduCQ6W3M3Ala03/Tw8kFhLEGxHwealuxejQLZqg0y4nsngohze7rnldfpPHQ1Y=",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountUser");

                    b.HasData(
                        new
                        {
                            AccountId = "e75a027a-bfa8-430f-a3f0-82629734d6e8",
                            UserId = "3b6ccf20-922f-42f1-ac31-92af6cd03aea"
                        },
                        new
                        {
                            AccountId = "ddad3b28-5a76-44fc-8a3f-ac3ad13da419",
                            UserId = "83928c30-2194-46a8-8e14-74a5e8fc98b6"
                        },
                        new
                        {
                            AccountId = "6b9a30fb-146c-47d7-af09-8b826212b329",
                            UserId = "618963b2-d047-4be9-81c4-ad1a048c32f2"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introdution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CurriculumVitae");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = "7b815bf5-f370-4baf-b4d4-81e48727e522",
                            Name = "Quận Ninh Kiều",
                            ProvinceId = "5f0986c4-8761-48df-9fbd-6f8efa949214"
                        },
                        new
                        {
                            Id = "9bec27cb-0712-405f-bac1-88c6fc3f9e70",
                            Name = "Quận Bình Thuỷ",
                            ProvinceId = "5f0986c4-8761-48df-9fbd-6f8efa949214"
                        },
                        new
                        {
                            Id = "559535fb-88e5-48ea-b74c-0c5c62cde688",
                            Name = "Quận Cái Răng",
                            ProvinceId = "5f0986c4-8761-48df-9fbd-6f8efa949214"
                        },
                        new
                        {
                            Id = "e434d09b-9014-4f1d-9e27-b7d7c0a8de5c",
                            Name = "Quận Thốt Nốt",
                            ProvinceId = "5f0986c4-8761-48df-9fbd-6f8efa949214"
                        },
                        new
                        {
                            Id = "af5e616d-bc42-4379-9184-4e66f5b28e58",
                            Name = "Quận Ô Môn",
                            ProvinceId = "5f0986c4-8761-48df-9fbd-6f8efa949214"
                        },
                        new
                        {
                            Id = "5f882947-424f-4cb5-85ae-c662740554fd",
                            Name = "Quận Liên Chiểu",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "338f26fe-ac3f-40ec-b746-8cc51caa5a2f",
                            Name = "Quận Thanh Khê",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "3f35c3db-2648-4d19-b85e-204fd36decc7",
                            Name = "Quận Hải Châu",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "cd828f83-042b-41aa-a7e3-cff1c353c2d9",
                            Name = "Quận Sơn Trà",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "4c1c3aca-fca8-4fec-8b6c-e6d941bc29dc",
                            Name = "Quận Ngũ Hành Sơn",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "624a7459-8fab-46e9-a9d7-aa780cf1eb89",
                            Name = "Quận Cẩm Lệ",
                            ProvinceId = "41dc8467-cdeb-43df-a77b-c6deef848529"
                        },
                        new
                        {
                            Id = "4e3ece98-07a6-428d-97fe-b4ed3c306c87",
                            Name = "Quận Ba Đình",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "1a036894-f659-44a5-bc19-f0708d7ab957",
                            Name = "Quận Hoàn Kiếm",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "496ef908-e4ba-4ffc-8ff1-904422dff7eb",
                            Name = "Quận Tây Hồ",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "19473dac-5d3a-44f4-9469-290976247b8e",
                            Name = "Quận Long Biên",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "45b19cf4-5e28-4bc2-b86b-f06ba8b1889e",
                            Name = "Quận Cầu Giấy",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "013b2311-dc23-477b-9395-76eb7b970f31",
                            Name = "Quận Đống Đa",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "b67ce97c-06c0-4e58-a010-96641a828a3f",
                            Name = "Quận Hai Bà Trưng",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "8a3aa266-e44d-4f3f-90a7-92bd86925063",
                            Name = "Quận Hoàng Mai",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "c28dcb2a-2be0-4943-960c-3e6779b5b63d",
                            Name = "Quận Thanh Xuân",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "9acc8823-07d5-45ae-84f4-62e725135c9a",
                            Name = "Quận Nam Từ Liêm",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "98481f8d-c528-48fd-bde7-c5cf458b9224",
                            Name = "Quận Bắc Từ Liêm",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "e0080ee6-48b3-46d2-9c25-a4700032b403",
                            Name = "Quận Hà Đông",
                            ProvinceId = "3de3bd37-c588-4ccd-9c10-805851893475"
                        },
                        new
                        {
                            Id = "0cdcb0f6-db65-465f-bc47-1a17e97486d1",
                            Name = "Quận Hồng Bàng",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "a242cfcb-7e77-4075-b09c-281dc6cacdaf",
                            Name = "Quận Ngô Quyền",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "c6d0a093-8cdb-4bc7-b409-4ab0d7d9e598",
                            Name = "Quận Lê Chân",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "de9c3115-52e9-4724-9766-bfba6cad2691",
                            Name = "Quận Hải An",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "7e7537b9-b6c1-4e4e-ae1e-2130305c44cd",
                            Name = "Quận Kiến An",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "3a2924b8-ef89-41a3-9e72-4ef17b448bbc",
                            Name = "Quận Đồ Sơn",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "b613cb4a-638e-4130-b22d-6cd0d9a29dea",
                            Name = "Quận Dương Kinh",
                            ProvinceId = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730"
                        },
                        new
                        {
                            Id = "cc2f7b5e-3f1f-45b1-90e3-60f660ad3c25",
                            Name = "Quận 1",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "e4494246-3939-475d-b8ca-20a87894cbde",
                            Name = "Quận 2",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "c96f7058-1531-4cc9-ae55-0cde60fc33af",
                            Name = "Quận 3",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "20c64b52-4b7c-4c76-8e43-1fe6068db681",
                            Name = "Quận 4",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "65a2b53b-de13-4999-9d56-6a870ad044e5",
                            Name = "Quận 5",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "4cbbfc10-c264-4809-9e61-bdaa9169f44a",
                            Name = "Quận 6",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "3ae7cd5b-13a6-4c5e-a723-ae59352b2b60",
                            Name = "Quận 7",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "3cc9ad8b-1030-4675-bab8-1feb96c36db8",
                            Name = "Quận 8",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "242b4442-5546-4a45-b55b-b66f55e8b118",
                            Name = "Quận 9",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "2a684023-c2a4-46c1-9656-816ba3bdb5d9",
                            Name = "Quận 10",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "4511a11d-5c47-4d80-bd00-f9a356224092",
                            Name = "Quận 11",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "b87a29fe-17b4-44f6-b987-b88a25671a2b",
                            Name = "Quận 12",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "3e3fd2d1-79ac-4317-a2e0-3b7be17dae9d",
                            Name = "Quận Gò Vấp",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "4b904219-622b-4be8-900a-bdbd00d7f743",
                            Name = "Quận Bình Thạnh",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "1707b38a-1007-49ce-a30d-df379bb27c10",
                            Name = "Quận Tân Bình",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "7962e6e3-7d09-4b4c-b94b-b1b5df292012",
                            Name = "Quận Tân Phú",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "b77b7606-d3f4-4f8c-8365-fc79e8b0e33b",
                            Name = "Quận Phú Nhuận",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "f8e7044f-6efa-4a4a-8c04-69674098ce57",
                            Name = "Quận Thủ Đức",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        },
                        new
                        {
                            Id = "92eda654-9cd9-4afe-8f5a-6816a56011c1",
                            Name = "Quận Bình Tân",
                            ProvinceId = "307f175e-ec2a-4905-9668-020ec7c93a8c"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = "70434a5b-998a-4367-8cdf-ad8159ebd3b5",
                            Exp = "Tất cả kinh nghiệm"
                        },
                        new
                        {
                            Id = "79ce8ed8-eac9-4f48-863e-0ab9963c8c01",
                            Exp = "Chưa có kinh nghiệm"
                        },
                        new
                        {
                            Id = "529e1e07-e1c0-4689-a568-9c302f57034e",
                            Exp = "Dưới 1 năm"
                        },
                        new
                        {
                            Id = "2d96ef3c-907d-4c18-82f3-483c8f441c0d",
                            Exp = "Từ 1-2 năm"
                        },
                        new
                        {
                            Id = "5bae8db6-098d-4de6-97de-2e635d5ce709",
                            Exp = "Từ 2-3 năm"
                        },
                        new
                        {
                            Id = "0618e5f5-ed7b-4902-9fef-430e47803546",
                            Exp = "Từ 3-5 năm"
                        },
                        new
                        {
                            Id = "c847f343-8d49-4bf0-8822-dfe57e0ece16",
                            Exp = "Từ 5-10 năm"
                        },
                        new
                        {
                            Id = "3ff7e0b6-dc4e-4719-844a-9040cb2e6dba",
                            Exp = "Trên 10 năm"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.HubConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HubConnection");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("JobAddress");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobCareer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCareer");

                    b.HasData(
                        new
                        {
                            Id = "48a4e6a5-7cbf-4d38-860d-eeb4839cf7ee",
                            Career = "Tất cả ngành nghề"
                        },
                        new
                        {
                            Id = "fa2b3843-68a5-41bb-8d93-d3217cd4b38c",
                            Career = "An toàn lao động"
                        },
                        new
                        {
                            Id = "93eaa686-1e1c-46f3-8e3a-21983fcdf9b7",
                            Career = "Bán hàng kỹ thuật"
                        },
                        new
                        {
                            Id = "c944a834-cb57-4cd3-941d-6288e6c90c85",
                            Career = "Bán lẻ / bán sỉ"
                        },
                        new
                        {
                            Id = "7a3e8fa8-9683-49e8-a3a6-1664f8d1fba4",
                            Career = "Báo chí / Truyền hình"
                        },
                        new
                        {
                            Id = "b10943cc-1201-407a-87ca-53ab79b29f12",
                            Career = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "53eeffd7-e0dd-45fd-b422-641d23f0d3d5",
                            Career = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "4603d4fb-9c3f-4aa0-a1cd-0bfa4a2092b8",
                            Career = "Bất động sản"
                        },
                        new
                        {
                            Id = "47d10397-52ae-4764-8ad0-23086dcb635d",
                            Career = "Biên / Phiên dịch"
                        },
                        new
                        {
                            Id = "ab9b6430-4696-453a-9094-9768de940210",
                            Career = "Bưu chính - Viễn thông"
                        },
                        new
                        {
                            Id = "81066e08-259d-4536-879f-9e3116fce1b0",
                            Career = "Chứng khoán / Vàng / Ngoại tệ"
                        },
                        new
                        {
                            Id = "8ec234ae-ea5b-421d-8f93-7f324afcab9b",
                            Career = "Cơ khí / Chế tạo / Tự động hóa"
                        },
                        new
                        {
                            Id = "992325bd-0f9f-4f1d-aebb-7c6e6465d105",
                            Career = "Công nghệ cao"
                        },
                        new
                        {
                            Id = "1febb0fc-4b8b-4fed-8a4e-bf375c5d7e03",
                            Career = "Công nghệ Ô tô"
                        },
                        new
                        {
                            Id = "f1bfa9ef-d0c3-464b-bc17-68f1c44d58c7",
                            Career = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = "daff4621-a121-4085-a1a7-54b4ace2f2af",
                            Career = "Dầu khí/Hóa chất"
                        },
                        new
                        {
                            Id = "7e30face-75df-43bf-a846-1ad5f53008bb",
                            Career = "Dệt may / Da giày"
                        },
                        new
                        {
                            Id = "ec506cbe-4d63-43b4-abc4-f74378122ba5",
                            Career = "Địa chất / Khoáng sản"
                        },
                        new
                        {
                            Id = "40490d97-2a5a-43f6-b478-8b8d706098d7",
                            Career = "Dịch vụ khách hàng"
                        },
                        new
                        {
                            Id = "7dcd81ab-290d-4bd3-9dca-ccd6c8cec093",
                            Career = "Điện / Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "39363182-ed24-4181-b2e8-7f96e879b98b",
                            Career = "Điện tử viễn thông"
                        },
                        new
                        {
                            Id = "bb8f3f0b-0fd2-4286-ba25-723a68929717",
                            Career = "Du lịch"
                        },
                        new
                        {
                            Id = "bf11d7e2-1316-433c-a4f2-44741b2cb79b",
                            Career = "Dược phẩm / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "df6583b2-dbf7-4476-83c5-68fef4dd1218",
                            Career = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "0ac74cd5-7cfc-451a-889d-1c87d7f47b1b",
                            Career = "Hàng cao cấp"
                        },
                        new
                        {
                            Id = "1e2d74a0-dd05-46e0-8772-40f2c3bfdb37",
                            Career = "Hàng gia dụng"
                        },
                        new
                        {
                            Id = "8aa0a7fa-8a90-4140-b969-3d13ab55bf32",
                            Career = "Hàng hải"
                        },
                        new
                        {
                            Id = "0317293f-122f-42c1-ab38-a9a886a95222",
                            Career = "Hàng không"
                        },
                        new
                        {
                            Id = "da2b4404-339d-4188-80f9-d9e42250cf3e",
                            Career = "Hàng tiêu dùng"
                        },
                        new
                        {
                            Id = "0807ea3f-e875-4936-8daf-28bc573fdb5c",
                            Career = "Hành chính / Văn phòng"
                        },
                        new
                        {
                            Id = "548c6719-f6d0-4da0-a7b0-fa2c08047fa7",
                            Career = "Hoá học / Sinh học"
                        },
                        new
                        {
                            Id = "e17b46a8-19e8-4e56-af24-08efc66e7aa7",
                            Career = "Hoạch định / Dự án"
                        },
                        new
                        {
                            Id = "b9883d92-c1ae-4c7a-9f6f-5a621a94f327",
                            Career = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "0e4888a8-7f00-47c8-9739-27b248ab5bdd",
                            Career = "IT Phần cứng / Mạng"
                        },
                        new
                        {
                            Id = "799fd7e4-a4e5-49a3-8858-2ba477df89e7",
                            Career = "IT phần mềm"
                        },
                        new
                        {
                            Id = "17719137-36df-4746-95f6-99de8e89d10a",
                            Career = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "830de325-7ae1-417c-a5ee-8a712cf58958",
                            Career = "Khách sạn / Nhà hàng"
                        },
                        new
                        {
                            Id = "5f4a455e-b2a5-4178-ab67-e42667ed0200",
                            Career = "Kiến trúc"
                        },
                        new
                        {
                            Id = "48c894a7-7693-4945-9c56-dcd0f8eaa534",
                            Career = "Kinh doanh / Bán hàng"
                        },
                        new
                        {
                            Id = "e65dde36-9376-4a34-a8b1-8171b9971c90",
                            Career = "Logistics"
                        },
                        new
                        {
                            Id = "559a4411-632e-4a5d-bed0-f6f133509429",
                            Career = "Luật / Pháp lý"
                        },
                        new
                        {
                            Id = "8f58e47d-3cb7-4542-a9c5-f8bffee14461",
                            Career = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "73f3a77a-caa7-4796-9135-396e8e531402",
                            Career = "Môi trường / Xử lý chất thải"
                        },
                        new
                        {
                            Id = "bf490c13-caaa-418d-ae78-1198047e9d3f",
                            Career = "Mỹ phẩm / Trang sức"
                        },
                        new
                        {
                            Id = "218376a1-3e1f-49b2-aa8e-ce8d29233750",
                            Career = "Mỹ thuật / Nghệ thuật / Điện ảnh"
                        },
                        new
                        {
                            Id = "e42ddef5-a0b5-479d-a3db-34255e94cada",
                            Career = "Ngân hàng / Tài chính"
                        },
                        new
                        {
                            Id = "6e45d8b4-7a90-4671-8a5c-dde9dc3605e9",
                            Career = "Ngành nghề khác"
                        },
                        new
                        {
                            Id = "f9d21a34-cd17-4834-85d4-55189a7198c5",
                            Career = "NGO / Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "255451e7-f8fb-465b-8998-9b78d141ca11",
                            Career = "Nhân sự"
                        },
                        new
                        {
                            Id = "69aebe57-5658-4ebb-9b79-e2541fe0b1a8",
                            Career = "Nông / Lâm / Ngư nghiệp"
                        },
                        new
                        {
                            Id = "ea67ba93-ffbb-4f0a-ba4f-a513f62ecbed",
                            Career = "Phi chính phủ / Phi lợi nhuận"
                        },
                        new
                        {
                            Id = "6301387a-5a7e-40a4-9e7e-7e304e254cfa",
                            Career = "Quản lý chất lượng (QA/QC)"
                        },
                        new
                        {
                            Id = "5c1a63db-403b-47fe-8ba9-a3dc200b47ba",
                            Career = "Quản lý điều hành"
                        },
                        new
                        {
                            Id = "f56d586b-7faa-474e-b40e-008c18141415",
                            Career = "Sản phẩm công nghiệp"
                        },
                        new
                        {
                            Id = "6539d92d-b7f1-43f2-9930-6230e061ee94",
                            Career = "Sản xuất"
                        },
                        new
                        {
                            Id = "1bee17c5-3789-47e1-a475-f70a8205bb75",
                            Career = "Spa / Làm đẹp"
                        },
                        new
                        {
                            Id = "12f488d3-25ea-4442-b9d4-b915ecd0d0f7",
                            Career = "Tài chính / Đầu tư"
                        },
                        new
                        {
                            Id = "4894bc84-7f94-4f33-9e0c-48a17db81c88",
                            Career = "Thiết kế đồ họa"
                        },
                        new
                        {
                            Id = "659b3522-874f-4ba9-acbb-e2fc61c9d125",
                            Career = "Thiết kế nội thất"
                        },
                        new
                        {
                            Id = "ab3e81c4-76bc-4c7d-a9b6-bc0c51c6d762",
                            Career = "Thời trang"
                        },
                        new
                        {
                            Id = "e1d43503-83b4-422f-a0d0-e6c7e629bf16",
                            Career = "Thư ký / Trợ lý"
                        },
                        new
                        {
                            Id = "f4c1d51d-3fc0-4920-8884-3903f5848fc5",
                            Career = "Thực phẩm / Đồ uống"
                        },
                        new
                        {
                            Id = "fc997b4c-e21e-4111-8c94-5abd30fbf600",
                            Career = "Tổ chức sự kiện / Quà tặng"
                        },
                        new
                        {
                            Id = "a4346f57-50c1-4637-a7da-a0cddda10d08",
                            Career = "Tư vấn"
                        },
                        new
                        {
                            Id = "db9f7bac-9878-487c-8242-00b5e4c18c92",
                            Career = "Vận tải / Kho vận"
                        },
                        new
                        {
                            Id = "5fc1f6c8-9a42-4bb6-a7e5-eb09012501d9",
                            Career = "Xây dựng"
                        },
                        new
                        {
                            Id = "4aad94b9-8dde-4d11-97cb-edfd3f31f4ac",
                            Career = "Xuất nhập khẩu"
                        },
                        new
                        {
                            Id = "7feb6f2a-d7cf-4d03-bbec-6579ae5c3ddd",
                            Career = "Y tế / Dược"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobField");

                    b.HasData(
                        new
                        {
                            Id = "944ef24f-d127-4da5-9aaa-c017d414b037",
                            Field = "Tất cả lĩnh vực"
                        },
                        new
                        {
                            Id = "32d358eb-4030-45ca-add4-a4dd0d6c4608",
                            Field = "Agency (Design/Development)"
                        },
                        new
                        {
                            Id = "01046d87-d172-4444-bed2-5252ef32f72c",
                            Field = "Agency (Marketing/Advertising)"
                        },
                        new
                        {
                            Id = "48497ebf-43f4-4133-a29f-fdfc4b0083c7",
                            Field = "Bán lẻ - Hàng tiêu dùng - FMCG"
                        },
                        new
                        {
                            Id = "57cb40bd-da24-401d-b8ab-f505de442c3c",
                            Field = "Bảo hiểm"
                        },
                        new
                        {
                            Id = "19b5a718-56aa-4794-a21d-6f975ca7ccb6",
                            Field = "Bảo trì / Sửa chữa"
                        },
                        new
                        {
                            Id = "22857b19-1a25-4a8f-bab4-151dbcd96c1f",
                            Field = "Bất động sản"
                        },
                        new
                        {
                            Id = "45edcf10-b743-4579-b550-235bc371f8cb",
                            Field = "Chứng khoán"
                        },
                        new
                        {
                            Id = "8b069135-b224-4d9a-a3b0-729e4e75122c",
                            Field = "Cơ khí"
                        },
                        new
                        {
                            Id = "d14225f5-17ef-4597-a79f-93a157caef0e",
                            Field = "Cơ quan nhà nước"
                        },
                        new
                        {
                            Id = "e4fe9798-9227-4741-a8fa-7346f033ce65",
                            Field = "Du lịch"
                        },
                        new
                        {
                            Id = "e952dd9d-14a3-43f1-b394-ba4bcbcaaff7",
                            Field = "Dược phẩm / Y tế / Công nghệ sinh học"
                        },
                        new
                        {
                            Id = "bc464176-348c-4391-8015-978211aa15bb",
                            Field = "Điện tử / Điện lạnh"
                        },
                        new
                        {
                            Id = "a73102a4-5c75-4866-9264-3e42e39f2955",
                            Field = "Giải trí"
                        },
                        new
                        {
                            Id = "6f0718d7-0d25-484c-8f0e-13fa6c4eb590",
                            Field = "Giáo dục / Đào tạo"
                        },
                        new
                        {
                            Id = "1cf5279f-855c-4088-85db-a0b0fa7f73f9",
                            Field = "In ấn / Xuất bản"
                        },
                        new
                        {
                            Id = "564a865e-b9b0-4514-b351-4881b333ea92",
                            Field = "Internet / Online"
                        },
                        new
                        {
                            Id = "d6e7353c-fc17-44c4-85ba-f41c204b6589",
                            Field = "IT - Phần cứng"
                        },
                        new
                        {
                            Id = "c78fb66b-b814-4622-b902-54c39df0ef84",
                            Field = "IT - Phần mềm"
                        },
                        new
                        {
                            Id = "23680af2-a8a1-403f-acbd-a3e5053aa912",
                            Field = "Kế toán / Kiểm toán"
                        },
                        new
                        {
                            Id = "94363b3a-83fc-47d9-a726-10e6435f30fb",
                            Field = "Khác"
                        },
                        new
                        {
                            Id = "9eb12e7d-daf6-4caf-9dac-e8708c7c44e1",
                            Field = "Logistics - Vận tải"
                        },
                        new
                        {
                            Id = "732b3ce6-49b1-4d79-b23a-aa3d0a24e03f",
                            Field = "Luật"
                        },
                        new
                        {
                            Id = "c4814505-8d49-4c99-a290-f83f0db955eb",
                            Field = "Marketing / Truyền thông / Quảng cáo"
                        },
                        new
                        {
                            Id = "0a722cc6-a6f7-4f8f-93bf-e702674d7f00",
                            Field = "Môi trường"
                        },
                        new
                        {
                            Id = "64464489-3616-4fe3-8e3b-97569cbe696b",
                            Field = "Năng lượng"
                        },
                        new
                        {
                            Id = "09300ab1-4de9-44ad-9c88-d51f4415751a",
                            Field = "Ngân hàng"
                        },
                        new
                        {
                            Id = "e11796e7-38ce-4f22-ad42-20d8da2a8612",
                            Field = "Nhà hàng / Khách sạn"
                        },
                        new
                        {
                            Id = "37bc2e75-03af-4b79-a12a-95d545b084d1",
                            Field = "Nhân sự"
                        },
                        new
                        {
                            Id = "ab8c756d-dfe6-44e0-be17-be25c7bd643d",
                            Field = "Nông Lâm Ngư nghiệp"
                        },
                        new
                        {
                            Id = "9187732c-8fbe-4491-b9c3-9348caaed3f7",
                            Field = "Sản xuất"
                        },
                        new
                        {
                            Id = "afdb1dea-6193-4792-9292-77153ae4df90",
                            Field = "Tài chính"
                        },
                        new
                        {
                            Id = "f12f84fb-dbeb-4640-9082-487965abe439",
                            Field = "Thiết kế / kiến trúc"
                        },
                        new
                        {
                            Id = "a1dc4c82-9898-4102-af1c-a0313a8f4636",
                            Field = "Thời trang"
                        },
                        new
                        {
                            Id = "34654014-34ef-4057-bc5b-7e2cde7ea240",
                            Field = "Thương mại điện tử"
                        },
                        new
                        {
                            Id = "15dfd8db-675a-4837-aa70-f0aab7a23c7b",
                            Field = "Tổ chức phi lợi nhuận"
                        },
                        new
                        {
                            Id = "350b3495-fab6-4270-bb7c-8073a680aa0f",
                            Field = "Tự động hóa"
                        },
                        new
                        {
                            Id = "785d1855-dd49-4bbb-8c8d-f6ae66b68814",
                            Field = "Tư vấn"
                        },
                        new
                        {
                            Id = "5551c8c0-ec8b-4e5f-bcb9-59d21090f3f6",
                            Field = "Viễn thông"
                        },
                        new
                        {
                            Id = "e48c3988-cf2f-40a7-9d1b-f398cd06a49d",
                            Field = "Xây dựng"
                        },
                        new
                        {
                            Id = "2ea855af-4759-4e42-ae8b-22e6296d8260",
                            Field = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobForm");

                    b.HasData(
                        new
                        {
                            Id = "1938a494-15e5-47d5-827d-64875d08c764",
                            Form = "Tất cả hình thức"
                        },
                        new
                        {
                            Id = "82d71796-7507-4e9a-b8d3-3a081a136fd8",
                            Form = "Toàn thời gian"
                        },
                        new
                        {
                            Id = "286d2a5a-88ec-41fc-b610-eb49767cec15",
                            Form = "Bán thời gian"
                        },
                        new
                        {
                            Id = "d4da3724-920a-4f55-aa8a-aba9cfcbe7f6",
                            Form = "Thực tập"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPosition");

                    b.HasData(
                        new
                        {
                            Id = "32f3e53b-8a3a-4fbc-8d7b-6ed443910097",
                            Position = "Tất cả vị trí"
                        },
                        new
                        {
                            Id = "c71c275a-0047-4133-8d61-4f459e725a6a",
                            Position = "Nhân viên"
                        },
                        new
                        {
                            Id = "d8bc4a41-9d2b-4142-bd30-fd61351ac9a6",
                            Position = "Trưởng nhóm"
                        },
                        new
                        {
                            Id = "d4e052c3-241c-4205-bd3a-ed5359eda713",
                            Position = "Trưởng / Phó phòng"
                        },
                        new
                        {
                            Id = "7b3b9401-0b9d-4428-bcaa-8d558813f272",
                            Position = "Quản lí / Giám sát"
                        },
                        new
                        {
                            Id = "fcb4f4e9-7fdf-4eb3-a339-63e8d5af048d",
                            Position = "Trưởng chi nhánh"
                        },
                        new
                        {
                            Id = "0cfca20f-157e-4563-b1ac-21193bca7b30",
                            Position = "Phó giám đốc"
                        },
                        new
                        {
                            Id = "78b5f795-d229-4792-a8ed-a69a63033154",
                            Position = "Giám đốc"
                        },
                        new
                        {
                            Id = "6adaac2d-d89e-47c7-8a96-15d07126af47",
                            Position = "Thực tập sinh"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecruitmentCVCurriculumVitaeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecruitmentCVRecruitmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RecruitmentCVRecruitmentId", "RecruitmentCVCurriculumVitaeId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = "711a1042-c09a-4f6d-8763-e3507f610cb1",
                            Name = "Tất cả tỉnh thành"
                        },
                        new
                        {
                            Id = "d1bd7c7c-354c-4770-8385-b2e43973dd91",
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = "97290cd4-ef7e-4226-842d-ad8611a9bd64",
                            Name = "Bà Rịa-Vũng Tàu"
                        },
                        new
                        {
                            Id = "08c232e2-61e1-4f22-9ed9-79eb62d25bd7",
                            Name = "Bắc Giang"
                        },
                        new
                        {
                            Id = "0d08b49e-06d4-41c4-9c13-2eec36fde72d",
                            Name = "Bắc Kạn"
                        },
                        new
                        {
                            Id = "f867e8f8-666e-44fe-8d34-e1b56b6846d0",
                            Name = "Bạc Liêu"
                        },
                        new
                        {
                            Id = "0f5e8336-5727-4b71-99fa-622da9230ccf",
                            Name = "Bắc Ninh"
                        },
                        new
                        {
                            Id = "2dba2874-3822-41da-9a4d-748187b52307",
                            Name = "Bến Tre"
                        },
                        new
                        {
                            Id = "f28cfe8e-feac-4200-b70f-c07d11c6ec78",
                            Name = "Bình Định"
                        },
                        new
                        {
                            Id = "0ddd2a3b-afab-4188-a7b5-80e091d9ff41",
                            Name = "Bình Dương"
                        },
                        new
                        {
                            Id = "175667fe-e6cf-47e4-8c26-1aeabd2c9f22",
                            Name = "Bình Phước"
                        },
                        new
                        {
                            Id = "9e8e6358-f5f7-4d8a-85a6-9749dc4748cc",
                            Name = "Bình Thuận"
                        },
                        new
                        {
                            Id = "d17b344c-f8ba-403b-ab86-1a25aed0943b",
                            Name = "Cà Mau"
                        },
                        new
                        {
                            Id = "5f0986c4-8761-48df-9fbd-6f8efa949214",
                            Name = "Cần Thơ"
                        },
                        new
                        {
                            Id = "3e92e6c3-e1b9-40e6-aea7-9879d7b8a7e3",
                            Name = "Cao Bằng"
                        },
                        new
                        {
                            Id = "41dc8467-cdeb-43df-a77b-c6deef848529",
                            Name = "Đà Nẵng"
                        },
                        new
                        {
                            Id = "5a4cd04e-1ca6-4f01-80b7-13b42df91b67",
                            Name = "Đắk Lắk"
                        },
                        new
                        {
                            Id = "70c952a3-edf0-4abc-afe7-1bcd8ef224a8",
                            Name = "Đắk Nông"
                        },
                        new
                        {
                            Id = "cf9ed239-ec4d-45dc-b981-399c35feeb16",
                            Name = "Điện Biên"
                        },
                        new
                        {
                            Id = "7f07bacb-66f4-4a61-8d25-d6f774b44cc0",
                            Name = "Đồng Nai"
                        },
                        new
                        {
                            Id = "9783bb78-913c-43db-bc1f-0b992d5889e1",
                            Name = "Đồng Tháp"
                        },
                        new
                        {
                            Id = "50a13510-4caa-4920-8ef9-740d38c39ee5",
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = "9a32cc2c-acc8-4cb6-8699-48b5337e5f37",
                            Name = "Hà Giang"
                        },
                        new
                        {
                            Id = "3bdbb152-45d4-4f0b-8c43-14e63df2cd64",
                            Name = "Hà Nam"
                        },
                        new
                        {
                            Id = "3de3bd37-c588-4ccd-9c10-805851893475",
                            Name = "Hà Nội"
                        },
                        new
                        {
                            Id = "62d36a2e-c586-4f5d-b98f-9e32e7786930",
                            Name = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = "99912c78-d33b-450a-aeaa-b314726348f1",
                            Name = "Hải Dương"
                        },
                        new
                        {
                            Id = "5a6abc58-eafe-4bff-8fe1-0ff31ce79730",
                            Name = "Hải Phòng"
                        },
                        new
                        {
                            Id = "b215893e-f7ac-4f64-8b43-b0dccb383acb",
                            Name = "Hậu Giang"
                        },
                        new
                        {
                            Id = "7d31a645-af7c-4a48-87b2-ac337741559a",
                            Name = "Hòa Bình"
                        },
                        new
                        {
                            Id = "f7838fcb-5fa7-4796-9355-ae840d08397d",
                            Name = "Hưng Yên"
                        },
                        new
                        {
                            Id = "b562472d-fc7d-421b-8d57-8926ce68d7a1",
                            Name = "Khánh Hòa"
                        },
                        new
                        {
                            Id = "dd178d6c-ab38-4674-9f3a-7b31cc037791",
                            Name = "Kiên Giang"
                        },
                        new
                        {
                            Id = "8ad2cb42-fb77-4447-911a-3484705ef689",
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = "bec7979e-56f7-4ec8-a5f4-c29247cc1e19",
                            Name = "Lai Châu"
                        },
                        new
                        {
                            Id = "6b55023b-67c5-4f62-bf23-fdd8c290cadc",
                            Name = "Lâm Đồng"
                        },
                        new
                        {
                            Id = "fb3a2d04-c115-4cdb-963b-7e448e153e33",
                            Name = "Lạng Sơn"
                        },
                        new
                        {
                            Id = "d08b918c-c958-4cad-8c33-48b228efee84",
                            Name = "Lào Cai"
                        },
                        new
                        {
                            Id = "497c9470-2b22-4eb1-bbdb-45af5eb67e42",
                            Name = "Long An"
                        },
                        new
                        {
                            Id = "5b3a34a2-b6e1-4fb6-bbbd-15295e28a16a",
                            Name = "Nam Định"
                        },
                        new
                        {
                            Id = "e5434957-d8db-4364-8da6-2781b8251d72",
                            Name = "Nghệ An"
                        },
                        new
                        {
                            Id = "f29d8c0f-1dc6-48f1-8f6a-a2938ddd11ce",
                            Name = "Ninh Bình"
                        },
                        new
                        {
                            Id = "2c4a60cc-29be-4991-9393-c114b91ef999",
                            Name = "Ninh Thuận"
                        },
                        new
                        {
                            Id = "d1fe24c1-e18b-4694-8f1a-8b6006c6d844",
                            Name = "Phú Thọ"
                        },
                        new
                        {
                            Id = "2a4055e5-fca2-4cc0-adf3-ca35404edd60",
                            Name = "Phú Yên"
                        },
                        new
                        {
                            Id = "3972691d-bede-4b11-b680-09326c1653dd",
                            Name = "Quảng Bình"
                        },
                        new
                        {
                            Id = "af2b8de5-cf93-4acd-b72c-01254bc2e7ba",
                            Name = "Quảng Nam"
                        },
                        new
                        {
                            Id = "cd525cb4-f3e9-4968-91a0-7fc733350da9",
                            Name = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = "e30f9b9a-4d75-4590-85c7-e9ed521e0aa3",
                            Name = "Quảng Ninh"
                        },
                        new
                        {
                            Id = "6ca8b7d2-42e6-4114-b5d0-f349ee8966d9",
                            Name = "Quảng Trị"
                        },
                        new
                        {
                            Id = "e085bb33-ddf7-48a5-9fa8-06364bb8796f",
                            Name = "Sóc Trăng"
                        },
                        new
                        {
                            Id = "fcb840a3-5fb5-4c6d-8348-660823cf139c",
                            Name = "Sơn La"
                        },
                        new
                        {
                            Id = "6713a4b5-38b0-4c19-b13c-31d1149afc3e",
                            Name = "Tây Ninh"
                        },
                        new
                        {
                            Id = "e5e555cd-cea0-452a-a443-426d787c84e5",
                            Name = "Thái Bình"
                        },
                        new
                        {
                            Id = "1012b77f-1b3c-4218-8dee-bdd3bf80704b",
                            Name = "Thái Nguyên"
                        },
                        new
                        {
                            Id = "b9934fe7-065d-43a5-8174-90c149fbc166",
                            Name = "Thanh Hóa"
                        },
                        new
                        {
                            Id = "1ae68c87-f646-43f9-88e6-ed405bb8d457",
                            Name = "Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = "ac9cfe94-86a5-45bc-bc4e-4337903afde6",
                            Name = "Tiền Giang"
                        },
                        new
                        {
                            Id = "307f175e-ec2a-4905-9668-020ec7c93a8c",
                            Name = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = "a77fe4f0-d207-4e1b-8e2b-aabc387586b9",
                            Name = "Trà Vinh"
                        },
                        new
                        {
                            Id = "e7f7a193-e194-495a-a4d9-214c4275d794",
                            Name = "Tuyên Quang"
                        },
                        new
                        {
                            Id = "31794c62-6614-40bf-a7cb-af78351e6a66",
                            Name = "Vĩnh Long"
                        },
                        new
                        {
                            Id = "72c55f14-cc20-4c9f-898b-88cec83782bf",
                            Name = "Vĩnh Phúc"
                        },
                        new
                        {
                            Id = "6e2d0804-6cb0-4ebe-a1f7-137bdb653f0e",
                            Name = "Yên Bái"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("JobAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobCareerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobFieldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobPositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("JobCareerId");

                    b.HasIndex("JobFieldId");

                    b.HasIndex("JobFormId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.Property<string>("RecruitmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurriculumVitaeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsView")
                        .HasColumnType("bit");

                    b.HasKey("RecruitmentId", "CurriculumVitaeId");

                    b.HasIndex("CurriculumVitaeId");

                    b.ToTable("RecruitmentCV");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "c2a0726f-8aa6-4908-acc5-4bc0c729be6a",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "4afc488c-c376-419f-832a-1489672d3032",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            Id = "2392dcd4-ac7f-4641-ab1c-46ffb86a8940",
                            RoleName = "Employer"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "3b6ccf20-922f-42f1-ac31-92af6cd03aea",
                            Email = "cvlookup.sgu.2023@gmail.com",
                            Username = "General Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleId = "c2a0726f-8aa6-4908-acc5-4bc0c729be6a",
                            UserId = "3b6ccf20-922f-42f1-ac31-92af6cd03aea"
                        },
                        new
                        {
                            RoleId = "2392dcd4-ac7f-4641-ab1c-46ffb86a8940",
                            UserId = "83928c30-2194-46a8-8e14-74a5e8fc98b6"
                        },
                        new
                        {
                            RoleId = "4afc488c-c376-419f-832a-1489672d3032",
                            UserId = "618963b2-d047-4be9-81c4-ad1a048c32f2"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Candidate", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Candidate");

                    b.HasData(
                        new
                        {
                            Id = "618963b2-d047-4be9-81c4-ad1a048c32f2",
                            Email = "cvlookup.sgu.2023_candidate@gmail.com",
                            Username = "Candidate Admin",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Employer", b =>
                {
                    b.HasBaseType("CVLookup_WebAPI.Models.Domain.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employer");

                    b.HasData(
                        new
                        {
                            Id = "83928c30-2194-46a8-8e14-74a5e8fc98b6",
                            Email = "cvlookup.sgu.2023_employer@gmail.com",
                            Username = "Employer Admin",
                            Address = "Admin",
                            Description = "Admin"
                        });
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.AccountUser", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.CurriculumVitae", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.District", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.JobAddress", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Notification", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.RecruitmentCV", "RecruitmentCV")
                        .WithMany()
                        .HasForeignKey("RecruitmentCVRecruitmentId", "RecruitmentCVCurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecruitmentCV");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Recruitment", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobAddress", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobCareer", "JobCareer")
                        .WithMany()
                        .HasForeignKey("JobCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobField", "JobField")
                        .WithMany()
                        .HasForeignKey("JobFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobForm", "JobForm")
                        .WithMany()
                        .HasForeignKey("JobFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Experience");

                    b.Navigation("JobAddress");

                    b.Navigation("JobCareer");

                    b.Navigation("JobField");

                    b.Navigation("JobForm");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.RecruitmentCV", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.CurriculumVitae", "CurriculumVitae")
                        .WithMany()
                        .HasForeignKey("CurriculumVitaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Recruitment", "Recruitment")
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumVitae");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Token", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.UserRole", b =>
                {
                    b.HasOne("CVLookup_WebAPI.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVLookup_WebAPI.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVLookup_WebAPI.Models.Domain.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
